/**
 * Extended Question Bank Seed Data (Part 3)
 * Surgery, Psychiatry, Emergency Medicine, Basic Sciences questions
 */

import { IQuestion } from "../types";

const createQuestion = (
  stem: string,
  options: { A: string; B: string; C: string; D: string; E: string },
  correctAnswer: "A" | "B" | "C" | "D" | "E",
  explanation: string,
  teachingPoints: string,
  references: string[],
  subject: string,
  topic: string,
  difficulty: "easy" | "medium" | "hard",
  isHighYield: boolean,
  subtopic?: string,
  tags?: string[],
): Partial<IQuestion> => {
  const answerMap = { A: 0, B: 1, C: 2, D: 3, E: 4 };
  return {
    questionText: stem,
    options: [options.A, options.B, options.C, options.D, options.E],
    correctAnswer: answerMap[correctAnswer],
    explanation,
    category: subject,
    subcategory: subtopic || topic,
    difficulty,
    tags: tags || [],
  };
};

// ============================================================================
// SURGERY QUESTIONS (12)
// ============================================================================

export const surgeryQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 45-year-old man presents with severe epigastric pain radiating to the back, nausea, and vomiting. Serum lipase is 1200 U/L. CT shows pancreatic edema and peripancreatic fluid. What is the most important initial management priority?",
    {
      A: "Emergency ERCP",
      B: "Aggressive IV fluid resuscitation",
      C: "Antibiotic prophylaxis",
      D: "Immediate laparotomy",
      E: "Enteral nutrition",
    },
    "B",
    `Aggressive IV fluid resuscitation is the most important initial priority in acute pancreatitis. Goal is to prevent pancreatic hypoperfusion and necrosis. Lactated Ringer's is preferred. Target urine output >0.5 mL/kg/hr.\n\nERCP is only for cholangitis or biliary obstruction. Prophylactic antibiotics are not recommended for sterile necrosis. Surgery is for infected necrosis or complications. Early enteral nutrition is important but fluid resuscitation takes priority in first 24 hours.`,
    "Acute pancreatitis: aggressive early fluid resuscitation (Lactated Ringer's) is critical in first 24 hours. Goal MAP >65 mmHg, urine output >0.5 mL/kg/hr.",
    ["ACG Acute Pancreatitis Guidelines 2013"],
    "Surgery",
    "General Surgery",
    "medium",
    true,
    "Acute Abdomen",
    ["pancreatitis", "fluid-resuscitation"],
  ),
  createQuestion(
    "A 28-year-old man presents with sudden severe testicular pain and swelling for 6 hours. The testis is tender, swollen, and high-riding with absent cremasteric reflex. What is the most appropriate management?",
    {
      A: "Antibiotics and scrotal elevation",
      B: "Doppler ultrasound",
      C: "Immediate surgical exploration",
      D: "Analgesia and observation",
      E: "Urine culture and antibiotics",
    },
    "C",
    `Immediate surgical exploration is indicated for suspected testicular torsion. Time is critical - testicular viability decreases significantly after 6 hours. The clinical picture (acute pain, high-riding testis, absent cremasteric reflex) is classic.\n\nUltrasound can confirm diagnosis but should not delay surgery if high suspicion. Antibiotics are for epididymo-orchitis which has more gradual onset and preserved cremasteric reflex. Observation risks testicular loss.`,
    "Testicular torsion: surgical emergency. Explore if high suspicion regardless of imaging. Salvage rates >90% if <6 hours, <10% if >24 hours.",
    ["AUA Testicular Torsion Guidelines"],
    "Surgery",
    "Urology",
    "medium",
    true,
    "Testicular Disorders",
    ["torsion", "surgical-emergency"],
  ),
  createQuestion(
    "A 65-year-old man presents with right lower quadrant pain, fever, and leukocytosis. CT shows colonic diverticulitis with abscess formation (5 cm). He is hemodynamically stable. What is the most appropriate initial management?",
    {
      A: "Immediate colectomy",
      B: "Percutaneous drainage and antibiotics",
      C: "Antibiotics alone",
      D: "Emergent Hartmann procedure",
      E: "Colonoscopy",
    },
    "B",
    `Percutaneous drainage and antibiotics is appropriate for diverticulitis with abscess >3 cm in a stable patient. This allows source control without immediate surgery.\n\nImmediate surgery is for perforation, obstruction, or failure of conservative management. Antibiotics alone are insufficient for abscess >3 cm. Hartmann procedure is for emergency resection. Colonoscopy is contraindicated acutely.`,
    "Diverticulitis with abscess >3 cm: percutaneous drainage + antibiotics. Surgery for complications or failed conservative management.",
    ["ASCRS Diverticulitis Guidelines 2020"],
    "Surgery",
    "General Surgery",
    "medium",
    true,
    "Acute Abdomen",
    ["diverticulitis", "abscess"],
  ),
  createQuestion(
    "A 30-year-old man is brought to ED after a motorcycle accident. He has open fracture of the right tibia with bone exposed, and 10 x 8 cm soft tissue defect. What is the most appropriate initial management?",
    {
      A: "Primary closure and casting",
      B: "Irrigation, debridement, provisional stabilization, delayed closure",
      C: "Immediate flap coverage",
      D: "External fixation only",
      E: "Amputation",
    },
    "B",
    `Open fracture management: urgent irrigation and debridement, provisional stabilization (often external fixation), antibiotics, tetanus prophylaxis, and delayed definitive closure.\n\nPrimary closure risks infection. Immediate flap coverage requires clean wound. External fixation alone is insufficient without debridement. Amputation is last resort for unsalvageable limb.`,
    "Open fractures: urgent debridement, antibiotics (usually 1st gen cephalosporin + aminoglycoside + penicillin if soil contamination), tetanus, stabilize, delayed closure.",
    ["OTA Open Fracture Guidelines"],
    "Surgery",
    "Orthopedics",
    "medium",
    true,
    "Fractures",
    ["open-fracture", "gustilo-anderson"],
  ),
  createQuestion(
    "A 55-year-old woman presents with a 2 cm breast mass. Core needle biopsy shows invasive ductal carcinoma, ER/PR positive, HER2 negative, grade 2. What is the most appropriate surgical treatment?",
    {
      A: "Modified radical mastectomy",
      B: "Breast conserving surgery plus sentinel node biopsy",
      C: "Total mastectomy with immediate reconstruction",
      D: "Excisional biopsy only",
      E: "Neoadjuvant chemotherapy first",
    },
    "B",
    `Breast conserving surgery (lumpectomy/wide local excision) with sentinel lymph node biopsy is appropriate for T1-2 N0 breast cancer. Adjuvant radiation follows BCS. This offers equivalent survival to mastectomy with better cosmesis.\n\nMastectomy is for large tumors, multicentric disease, or patient preference. Immediate reconstruction can follow mastectomy if desired. Excisional biopsy alone is inadequate cancer surgery. Neoadjuvant therapy is for locally advanced disease.`,
    "Early breast cancer: breast conserving surgery + sentinel node biopsy + radiation offers equivalent survival to mastectomy.",
    ["St. Gallen Breast Cancer Guidelines 2021"],
    "Surgery",
    "General Surgery",
    "medium",
    true,
    "Breast Surgery",
    ["breast-cancer", "bcs"],
  ),
  createQuestion(
    "A 45-year-old man presents with severe abdominal pain, guarding, and rebound tenderness. CT shows free intraperitoneal air and perforated duodenal ulcer. He is febrile and tachycardic. What is the most appropriate management?",
    {
      A: "Non-operative management with antibiotics",
      B: "Omental patch repair",
      C: "Truncal vagotomy and pyloroplasty",
      D: "Partial gastrectomy",
      E: "Percutaneous drainage",
    },
    "B",
    `Omental patch repair (Graham patch) is standard for perforated duodenal ulcer. Simple closure with omental patch has low morbidity and good outcomes.\n\nNon-operative management is for selected patients without peritonitis. Definitive ulcer surgery (vagotomy) is rarely needed with PPIs. Gastrectomy is excessive for simple perforation. Percutaneous drainage is for abscess, not free perforation.`,
    "Perforated duodenal ulcer: omental patch repair. Add H. pylori eradication and PPI therapy. Definitive surgery rarely needed now.",
    ["WSES Perforated Peptic Ulcer Guidelines"],
    "Surgery",
    "General Surgery",
    "medium",
    true,
    "Peptic Ulcer Disease",
    ["perforation", "omental-patch"],
  ),
  createQuestion(
    'A 70-year-old man presents with acute onset severe abdominal pain "out of proportion" to examination. He has atrial fibrillation. Lactate is elevated. CT shows pneumatosis intestinalis and portal venous gas. What is the diagnosis?',
    {
      A: "Acute mesenteric ischemia",
      B: "Small bowel obstruction",
      C: "Diverticulitis",
      D: "Pancreatitis",
      E: "Cholecystitis",
    },
    "A",
    `Acute mesenteric ischemia is the diagnosis. Key features: severe pain out of proportion to exam (indicates ischemia before infarction), atrial fibrillation (embolic source), pneumatosis (bowel wall gas = advanced ischemia), portal venous gas.\n\nThis is a surgical emergency. Mortality increases dramatically with delay. Other diagnoses don't explain the combination of findings.`,
    "Acute mesenteric ischemia: pain out of proportion, source of emboli (AF), elevated lactate, pneumatosis = surgical emergency.",
    ["WSES Mesenteric Ischemia Guidelines"],
    "Surgery",
    "General Surgery",
    "hard",
    true,
    "Acute Abdomen",
    ["mesenteric-ischemia", "emergency"],
  ),
  createQuestion(
    "A 25-year-old man presents with recurrent inguinal swelling that increases with coughing and straining. Examination shows a reducible swelling above and medial to the pubic tubercle. What is the most appropriate treatment?",
    {
      A: "Observation and truss",
      B: "Laparoscopic repair",
      C: "Open Lichtenstein tension-free mesh repair",
      D: "Bassini repair",
      E: "Emergency surgery",
    },
    "C",
    `Open Lichtenstein tension-free mesh repair is the gold standard for inguinal hernia. Low recurrence rates, can be done under local anesthesia, cost-effective.\n\nObservation risks strangulation. Laparoscopic repair is good for bilateral/recurrent hernias but more expensive. Bassini repair (non-mesh) has higher recurrence. Emergency surgery is for complications only.`,
    "Inguinal hernia: mesh repair (Lichtenstein) is gold standard. Laparoscopic for bilateral/recurrent. Repair symptomatic hernias.",
    ["European Hernia Society Guidelines"],
    "Surgery",
    "General Surgery",
    "easy",
    true,
    "Hernias",
    ["inguinal", "mesh-repair"],
  ),
  createQuestion(
    "A 60-year-old woman presents with jaundice, dark urine, and pale stools. Ultrasound shows dilated intrahepatic and extrahepatic bile ducts with a mass in the head of pancreas. What is the most appropriate management?",
    {
      A: "Chemotherapy alone",
      B: "Whipple procedure (pancreaticoduodenectomy)",
      C: "Biliary stent and palliative care",
      D: "Radiation therapy",
      E: "Liver transplantation",
    },
    "B",
    `Whipple procedure (pancreaticoduodenectomy) is the only potentially curative treatment for resectable pancreatic head cancer. Workup should assess resectability with CT chest/abdomen/pelvis.\n\nChemotherapy is adjuvant or for advanced disease. Stenting is for palliation of obstructive jaundice if unresectable. Radiation may be neoadjuvant or adjuvant. Transplantation is not standard for pancreatic cancer.`,
    "Resectable pancreatic head cancer: Whipple procedure offers only chance of cure. 5-year survival 20-25% after surgery.",
    ["NCCN Pancreatic Cancer Guidelines"],
    "Surgery",
    "General Surgery",
    "medium",
    true,
    "Pancreatic Cancer",
    ["whipple", "jaundice"],
  ),
  createQuestion(
    "A 35-year-old woman presents with right upper quadrant pain after eating fatty foods. Ultrasound shows multiple gallstones and a thickened gallbladder wall. She is afebrile. What is the most appropriate management?",
    {
      A: "Ursodeoxycholic acid",
      B: "Extracorporeal shock wave lithotripsy",
      C: "Laparoscopic cholecystectomy",
      D: "Antibiotics and observation",
      E: "Endoscopic sphincterotomy",
    },
    "C",
    `Laparoscopic cholecystectomy is the treatment of choice for symptomatic gallstones (biliary colic). Elective surgery prevents complications like cholecystitis, pancreatitis, and choledocholithiasis.\n\nMedical dissolution (ursodiol) is rarely used (low efficacy, recurrence). Lithotripsy is not standard for gallstones. Observation risks complications. ERCP with sphincterotomy is for choledocholithiasis.`,
    "Symptomatic gallstones: laparoscopic cholecystectomy is definitive treatment. Low morbidity, same-day or overnight stay.",
    ["SAGES Cholecystectomy Guidelines"],
    "Surgery",
    "General Surgery",
    "easy",
    true,
    "Gallbladder Disease",
    ["cholelithiasis", "laparoscopic"],
  ),
  createQuestion(
    "A 50-year-old man presents with intermittent claudication in the left calf after walking 200 meters. ABI is 0.65 on the left. He is a smoker with diabetes. What is the most appropriate initial management?",
    {
      A: "Immediate bypass surgery",
      B: "Endovascular angioplasty",
      C: "Best medical therapy and supervised exercise program",
      D: "Amputation",
      E: "Spinal cord stimulation",
    },
    "C",
    `Best medical therapy (antiplatelet, statin, BP/diabetes control, smoking cessation) plus supervised exercise is first-line for claudication. Most patients improve with conservative management.\n\nSurgery or endovascular intervention is for lifestyle-limiting claudication despite conservative management, or for critical limb ischemia. Amputation is for unsalvageable limb.`,
    "Claudication: best medical therapy + supervised exercise first-line. Revascularization for failed conservative management or critical limb ischemia.",
    ["ESVS Peripheral Arterial Disease Guidelines"],
    "Surgery",
    "Vascular Surgery",
    "medium",
    true,
    "Peripheral Artery Disease",
    ["claudication", "conservative"],
  ),
  createQuestion(
    "A 40-year-old man presents with progressive dysphagia to solids then liquids, regurgitation of undigested food, and halitosis. Barium swallow shows a dilated esophagus with bird's beak appearance at the lower end. What is the treatment?",
    {
      A: "Proton pump inhibitors",
      B: "Botulinum toxin injection",
      C: "Pneumatic dilation or laparoscopic Heller myotomy",
      D: "Esophagectomy",
      E: "Fundoplication alone",
    },
    "C",
    `Pneumatic dilation or laparoscopic Heller myotomy (+ partial fundoplication) are definitive treatments for achalasia. They disrupt the non-relaxing lower esophageal sphincter.\n\nPPIs treat GERD, not achalasia. Botulinum toxin is temporary (repeated injections needed). Esophagectomy is for end-stage disease. Fundoplication alone would worsen obstruction.`,
    "Achalasia: pneumatic dilation or Heller myotomy are definitive treatments. Botulinum toxin for poor surgical candidates.",
    ["SAGES Achalasia Guidelines"],
    "Surgery",
    "General Surgery",
    "medium",
    true,
    "Achalasia",
    ["myotomy", "pneumatic-dilation"],
  ),
];

// ============================================================================
// PSYCHIATRY QUESTIONS (10)
// ============================================================================

export const psychiatryQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 35-year-old woman presents with depressed mood, anhedonia, sleep disturbance, poor concentration, and fatigue for 6 weeks. She has passive suicidal ideation without plan. PHQ-9 score is 18. What is the first-line treatment?",
    {
      A: "Immediate hospitalization",
      B: "Cognitive behavioral therapy or SSRI",
      C: "Electroconvulsive therapy",
      D: "Lithium carbonate",
      E: "Benzodiazepines",
    },
    "B",
    `Moderate depression (PHQ-9 15-19): first-line is psychotherapy (CBT/IPT) or pharmacotherapy (SSRI like sertraline/escitalopram) or combination. Patient has suicidal ideation but no active plan.\n\nHospitalization is for active suicidal plan, inability to care for self, or psychosis. ECT is for severe/refractory depression or urgent need. Lithium is augmentation or bipolar. Benzodiazepines are not antidepressants.`,
    "Major depression: SSRI or psychotherapy first-line for moderate severity. Combination most effective. Monitor for suicidality.",
    ["RANZCP Depression Guidelines 2022"],
    "Psychiatry",
    "Mood Disorders",
    "easy",
    true,
    "Major Depression",
    ["ssri", "cbt"],
  ),
  createQuestion(
    "A 22-year-old man is brought by family for bizarre behavior. He reports hearing voices commenting on his actions for 3 months. He believes his thoughts are being broadcast on television. He has poor self-care and social withdrawal. What is the most likely diagnosis?",
    {
      A: "Bipolar disorder",
      B: "Major depression with psychotic features",
      C: "Schizophrenia",
      D: "Substance-induced psychosis",
      E: "Schizoaffective disorder",
    },
    "C",
    `Schizophrenia is most likely. First episode psychosis with: auditory hallucinations (voices), thought broadcasting (delusion), negative symptoms (poor self-care, withdrawal), duration >6 months (symptoms present 3 months with prodrome).\n\nBipolar would have mood episodes. Depression has prominent mood symptoms. Substance-induced requires temporal relationship. Schizoaffective requires mood episode concurrent with psychosis for majority of illness.`,
    "Schizophrenia: 2+ of hallucinations, delusions, disorganized speech/behavior, negative symptoms >6 months with functional decline.",
    ["DSM-5", "RANZCP Schizophrenia Guidelines 2016"],
    "Psychiatry",
    "Psychotic Disorders",
    "medium",
    true,
    "Schizophrenia",
    ["first-episode", "psychosis"],
  ),
  createQuestion(
    "A 30-year-old woman presents with recurrent panic attacks characterized by sudden onset palpitations, sweating, trembling, chest pain, and fear of dying. Episodes last 10-20 minutes. She avoids public places fearing embarrassment. What is the diagnosis?",
    {
      A: "Generalized anxiety disorder",
      B: "Panic disorder with agoraphobia",
      C: "Social anxiety disorder",
      D: "Acute coronary syndrome",
      E: "Somatic symptom disorder",
    },
    "B",
    `Panic disorder with agoraphobia: recurrent unexpected panic attacks with worry about future attacks and avoidance of situations (public places) where escape might be difficult.\n\nGAD has persistent worry, not discrete attacks. Social anxiety is fear of social scrutiny, not panic symptoms. ACS would have different pattern and investigations. Somatic symptom disorder has persistent somatic complaints.`,
    "Panic disorder: discrete panic attacks + anticipatory anxiety + avoidance. Agoraphobia often co-occurs. CBT and SSRIs are effective.",
    ["NICE Panic Disorder Guidelines"],
    "Psychiatry",
    "Anxiety Disorders",
    "easy",
    true,
    "Panic Disorder",
    ["agoraphobia", "cbt"],
  ),
  createQuestion(
    "A 25-year-old woman presents with binge eating (consuming large amounts of food with loss of control) twice weekly for 3 months, followed by self-induced vomiting. She is of normal weight but very concerned about body shape. What is the diagnosis?",
    {
      A: "Anorexia nervosa",
      B: "Bulimia nervosa",
      C: "Binge eating disorder",
      D: "Avoidant/restrictive food intake disorder",
      E: "Major depression",
    },
    "B",
    `Bulimia nervosa: recurrent binge eating + inappropriate compensatory behaviors (vomiting) + self-evaluation unduly influenced by body shape/weight, occurring at least weekly for 3 months, not exclusively during anorexia.\n\nAnorexia nervosa has low body weight. Binge eating disorder has binges without compensatory behaviors. ARFID lacks body image disturbance. Depression may coexist but doesn't explain the specific eating pattern.`,
    "Bulimia nervosa: binge + purge cycles. Normal body weight often. SSRIs (high dose fluoxetine) and CBT are effective treatments.",
    ["NICE Eating Disorders Guidelines 2017"],
    "Psychiatry",
    "Eating Disorders",
    "medium",
    true,
    "Bulimia Nervosa",
    ["binge", "purge"],
  ),
  createQuestion(
    "A 45-year-old man with bipolar disorder is on lithium. He presents with tremor, ataxia, confusion, and diarrhea. Lithium level is 2.5 mmol/L (therapeutic 0.6-1.0). Creatinine is elevated. What is the most appropriate management?",
    {
      A: "Continue lithium at lower dose",
      B: "Stop lithium and provide supportive care, consider hemodialysis",
      C: "Add valproate",
      D: "Increase fluid intake only",
      E: "Lithium level is therapeutic, continue current dose",
    },
    "B",
    `Lithium toxicity (level >2.0 with symptoms) requires immediate discontinuation of lithium and supportive care. Hemodialysis may be needed for severe toxicity, especially with renal impairment.\n\nContinuing lithium would worsen toxicity. Other mood stabilizers can be considered later. Fluid intake alone is insufficient for this severity. Level is clearly toxic.`,
    "Lithium toxicity: stop lithium, supportive care, hemodialysis if severe (>2.5, altered consciousness, renal failure).",
    ["RANZCP Bipolar Disorder Guidelines"],
    "Psychiatry",
    "Bipolar Disorder",
    "medium",
    true,
    "Lithium Toxicity",
    ["nephrotoxicity", "dialysis"],
  ),
  createQuestion(
    "A 19-year-old woman presents with fluctuating episodes of irritability, impulsivity, self-harm, unstable relationships, and chronic feelings of emptiness. She reports fear of abandonment. Symptoms started in adolescence. What is the most likely diagnosis?",
    {
      A: "Bipolar II disorder",
      B: "Major depression",
      C: "Borderline personality disorder",
      D: "Post-traumatic stress disorder",
      E: "Attention deficit disorder",
    },
    "C",
    `Borderline personality disorder: pattern of unstable relationships, self-image, and affect with marked impulsivity, fear of abandonment, self-harm, and chronic emptiness beginning in early adulthood.\n\nBipolar has distinct mood episodes. Depression lacks the relationship instability and impulsivity. PTSD requires trauma history. ADHD has different pattern of inattention/hyperactivity.`,
    "Borderline personality disorder: dialectical behavior therapy (DBT) is evidence-based treatment. SSRIs may help mood symptoms.",
    ["NICE Borderline Personality Disorder Guidelines"],
    "Psychiatry",
    "Personality Disorders",
    "hard",
    false,
    "Borderline Personality",
    ["dbt", "self-harm"],
  ),
  createQuestion(
    "A 28-year-old man presents with difficulty sleeping for 3 weeks after a car accident where he was trapped for 2 hours. He has nightmares about the accident, avoids driving, has hypervigilance, and feels emotionally numb. What is the diagnosis?",
    {
      A: "Acute stress disorder",
      B: "Post-traumatic stress disorder",
      C: "Adjustment disorder",
      D: "Generalized anxiety disorder",
      E: "Major depression",
    },
    "B",
    `PTSD: exposure to actual/threatened death/serious injury with intrusion symptoms (nightmares), avoidance, negative alterations in cognition/mood (emotional numbing), and marked alterations in arousal (hypervigilance) lasting >1 month.\n\nAcute stress disorder lasts 3 days to 1 month. Adjustment disorder has less specific symptoms. GAD has generalized worry. Depression lacks trauma-specific symptoms.`,
    "PTSD: trauma exposure + intrusion + avoidance + negative mood/cognition + hyperarousal >1 month. Trauma-focused CBT and SSRIs are effective.",
    ["NICE PTSD Guidelines 2018"],
    "Psychiatry",
    "Anxiety Disorders",
    "medium",
    true,
    "PTSD",
    ["trauma", "emdr"],
  ),
  createQuestion(
    "A 35-year-old man is brought by police after being found wandering. He is confused, disoriented, and hallucinating. He has tremor, tachycardia, and hypertension. He last drank alcohol 2 days ago. What is the diagnosis?",
    {
      A: "Wernicke encephalopathy",
      B: "Alcohol withdrawal delirium (delirium tremens)",
      C: "Alcoholic hallucinosis",
      D: "Korsakoff psychosis",
      E: "Hepatic encephalopathy",
    },
    "B",
    `Alcohol withdrawal delirium (delirium tremens) occurs 48-96 hours after last drink: delirium, autonomic hyperactivity (tachycardia, hypertension, fever), tremor, and hallucinations. Medical emergency with significant mortality.\n\nWernicke encephalopathy is triad of confusion, ataxia, ophthalmoplegia. Alcoholic hallucinosis has hallucinations without delirium. Korsakoff is chronic amnesia. Hepatic encephalopathy occurs with liver failure.`,
    "Delirium tremens: delirium + autonomic instability 48-96 hours post-alcohol. Medical emergency - benzodiazepines, thiamine, supportive care.",
    ["CIWA-Ar Protocol", "NICE Alcohol Withdrawal Guidelines"],
    "Psychiatry",
    "Substance Abuse",
    "hard",
    true,
    "Alcohol Withdrawal",
    ["delirium-tremens", "benzodiazepines"],
  ),
  createQuestion(
    "A 10-year-old boy presents with difficulty paying attention in school, easily distracted, unable to sit still, interrupting others, and fidgeting. Symptoms are present in multiple settings for >6 months. What is the first-line treatment?",
    {
      A: "Methylphenidate",
      B: "Atomoxetine",
      C: "Parent training and behavioral therapy",
      D: "Aripiprazole",
      E: "Fluoxetine",
    },
    "C",
    `Behavioral therapy and parent training are first-line for mild ADHD. For moderate-severe or persistence despite behavioral therapy, methylphenidate or other stimulants are effective.\n\nStimulants (methylphenidate, amphetamines) are most effective pharmacotherapy but behavioral interventions come first for young children. Atomoxetine is second-line. Antipsychotics and antidepressants are not first-line.`,
    "ADHD: behavioral interventions first for young children. Stimulants most effective pharmacotherapy. Multimodal treatment best.",
    ["NICE ADHD Guidelines 2018"],
    "Psychiatry",
    "Other Disorders",
    "medium",
    true,
    "ADHD",
    ["stimulants", "behavioral-therapy"],
  ),
  createQuestion(
    "A 60-year-old man with depression has failed two antidepressant trials. He has psychomotor retardation, severe anhedonia, and significant weight loss. He is not eating or drinking adequately. What is the most appropriate next step?",
    {
      A: "Start third antidepressant",
      B: "Add lithium augmentation",
      C: "Electroconvulsive therapy",
      D: "Refer to psychotherapy",
      E: "Increase dose of current antidepressant",
    },
    "C",
    `ECT is indicated for severe depression with: inadequate response to medications, severe psychomotor retardation, poor oral intake, catatonia, or high suicide risk. It is the most effective antidepressant treatment.\n\nFurther medication trials or augmentation may be tried but ECT has higher response rates in treatment-resistant depression with severity indicators. Psychotherapy is adjunctive.`,
    "ECT: most effective antidepressant treatment. Indicated for severe depression, treatment resistance, catatonia, high suicide risk, or medical emergency (poor intake).",
    ["RANZCP ECT Guidelines", "APA ECT Guidelines"],
    "Psychiatry",
    "Mood Disorders",
    "hard",
    true,
    "Treatment-Resistant Depression",
    ["ect", "neurostimulation"],
  ),
];

// ============================================================================
// EMERGENCY MEDICINE QUESTIONS (10)
// ============================================================================

export const emergencyQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 65-year-old man presents with crushing central chest pain radiating to the left arm, diaphoresis, and nausea. ECG shows ST elevation in leads V1-V4. BP is 80/50 mmHg, HR 110 bpm. What is the most appropriate immediate management?",
    {
      A: "Aspirin and sublingual GTN",
      B: "Thrombolysis",
      C: "Primary PCI",
      D: "IV fluids and inotropes then primary PCI",
      E: "Morphine and oxygen",
    },
    "D",
    `Cardiogenic shock complicating STEMI requires hemodynamic support (fluids, inotropes if needed) plus emergent revascularization (primary PCI). Inotropes may be needed to achieve SBP >90 for PCI.\n\nPrimary PCI is still indicated but may need hemodynamic optimization. Thrombolysis is second-line. Aspirin and GTN are adjunctive. Morphine is no longer routine.`,
    "Cardiogenic shock in STEMI: urgent revascularization (PCI) + hemodynamic support. Mortality high without prompt intervention.",
    ["ESC STEMI Guidelines 2023"],
    "Emergency Medicine",
    "Cardiovascular Emergencies",
    "hard",
    true,
    "Acute MI",
    ["cardiogenic-shock", "primary-pci"],
  ),
  createQuestion(
    "A 25-year-old man presents with sudden onset severe shortness of breath and pleuritic chest pain after a long flight. He is tachypneic with O2 sat 88% on room air. BP is 90/60 mmHg, HR 130 bpm. What is the most appropriate immediate management?",
    {
      A: "CT pulmonary angiography",
      B: "Therapeutic dose LMWH and resuscitation",
      C: "Thrombolysis",
      D: "IV fluids",
      E: "D-dimer testing",
    },
    "B",
    `Massive/hemodynamically unstable PE requires immediate empiric anticoagulation (if no contraindications) and resuscitation. Further diagnostic testing should not delay treatment in high suspicion with hemodynamic compromise.\n\nCTPA is diagnostic but patient is unstable. Thrombolysis is considered for massive PE but heparin comes first. IV fluids may worsen RV failure. D-dimer is inappropriate in high probability.`,
    "Massive PE with hemodynamic compromise: immediate anticoagulation, resuscitation, consider thrombolysis or embolectomy.",
    ["ESC Pulmonary Embolism Guidelines 2019"],
    "Emergency Medicine",
    "Medical Emergencies",
    "hard",
    true,
    "Pulmonary Embolism",
    ["massive-pe", "thrombolysis"],
  ),
  createQuestion(
    "A 3-year-old child is brought in after ingesting 20 tablets of paracetamol 3 hours ago. The child is asymptomatic. What is the most appropriate management?",
    {
      A: "Observation and discharge",
      B: "Activated charcoal if within 1 hour",
      C: "N-acetylcysteine (NAC) based on Rumack-Matthew nomogram",
      D: "Gastric lavage",
      E: "Liver function tests only",
    },
    "C",
    `NAC is indicated if the ingested dose is potentially toxic (>150 mg/kg or >10g total) or if 4-hour level is above treatment line. In children, treat based on nomogram or if dose >150 mg/kg.\n\nObservation alone risks hepatotoxicity. Charcoal is effective if <1-2 hours. Gastric lavage rarely indicated. LFTs become abnormal after liver injury has occurred.`,
    "Paracetamol overdose: NAC if >150 mg/kg ingested or level above nomogram. Start NAC within 8 hours for best efficacy.",
    ["Toxbase/UKPID Paracetamol Guidelines"],
    "Emergency Medicine",
    "Medical Emergencies",
    "medium",
    true,
    "Poisoning",
    ["paracetamol", "nac"],
  ),
  createQuestion(
    "A 40-year-old man presents with anaphylaxis after a bee sting. He has urticaria, angioedema, bronchospasm, and BP 70/40 mmHg. What is the most appropriate immediate treatment?",
    {
      A: "H1 antihistamine",
      B: "H2 antihistamine",
      C: "Intramuscular adrenaline in lateral thigh",
      D: "Intravenous corticosteroids",
      E: "Nebulized beta-agonist",
    },
    "C",
    `IM adrenaline (epinephrine) 0.3-0.5 mg 1:1000 in lateral thigh is the first-line and most important treatment for anaphylaxis. It treats all aspects of the reaction. Antihistamines and steroids are adjunctive.\n\nAdrenaline should be given immediately for respiratory or cardiovascular compromise. IV route only in cardiac arrest setting. Repeat every 5-15 minutes if needed.`,
    "Anaphylaxis: IM adrenaline first-line. Lie flat with legs elevated. Adjuncts: antihistamines, steroids, bronchodilators.",
    ["WAO Anaphylaxis Guidelines 2020", "AACE Anaphylaxis Practice Parameter"],
    "Emergency Medicine",
    "Medical Emergencies",
    "easy",
    true,
    "Anaphylaxis",
    ["adrenaline", "epinephrine"],
  ),
  createQuestion(
    "A 55-year-old man presents with confusion, tachypnea, and Kussmaul breathing. Blood glucose is 28 mmol/L, pH 7.15, bicarbonate 12 mmol/L, ketones 4+. Serum osmolality is 310 mOsm/kg. What is the diagnosis?",
    {
      A: "Hyperosmolar hyperglycemic state",
      B: "Diabetic ketoacidosis",
      C: "Lactic acidosis",
      D: "Uremic acidosis",
      E: "Toxic alcohol ingestion",
    },
    "B",
    `DKA is diagnosed by: glucose >13.9 mmol/L, pH <7.30, bicarbonate <18 mmol/L, ketonemia/ketonuria. Kussmaul breathing is compensatory hyperventilation for metabolic acidosis.\n\nHHS has higher glucose (>33.3), higher osmolality (>320), and no/minimal ketosis. Lactic acidosis has elevated lactate. Uremic acidosis has elevated urea/creatinine. Toxic alcohol has increased osmolar gap.`,
    "DKA: hyperglycemia + ketosis + metabolic acidosis. Treat with IV fluids, insulin, potassium monitoring. Identify precipitant.",
    ["ADA DKA Guidelines 2021"],
    "Emergency Medicine",
    "Medical Emergencies",
    "medium",
    true,
    "DKA",
    ["insulin", "fluid-resuscitation"],
  ),
  createQuestion(
    "A 20-year-old man is brought in after a high-speed motorcycle accident. He is unresponsive with GCS 8 (E2 V2 M4). BP is 90/60, HR 120. What is the most appropriate immediate management priority?",
    {
      A: "CT head",
      B: "Endotracheal intubation",
      C: "Fluid resuscitation",
      D: "FAST examination",
      E: "Spinal immobilization",
    },
    "B",
    `Airway protection with endotracheal intubation is the priority for GCS ≤8 (patient cannot protect airway). This follows the ABC approach to trauma.\n\nCT head, fluid resuscitation, FAST, and spinal precautions are all important but securing the airway comes first in a patient with altered consciousness.`,
    "Trauma ABC: Airway first. Intubate if GCS ≤8, impending airway compromise, or respiratory failure.",
    ["ATLS Guidelines 10th Edition"],
    "Emergency Medicine",
    "Trauma",
    "medium",
    true,
    "Head Trauma",
    ["airway", "gcs"],
  ),
  createQuestion(
    "A 30-year-old man presents with severe burns to chest and both arms after a house fire. Burn area covers 36% total body surface area using rule of nines. He has soot in mouth and singed nasal hairs. What is the additional concern?",
    {
      A: "Carbon monoxide poisoning",
      B: "Cyanide poisoning",
      C: "Inhalation injury",
      D: "All of the above",
      E: "None of the above",
    },
    "D",
    `Burns with enclosed space fire have high risk of: inhalation injury (thermal or chemical injury to airways), carbon monoxide poisoning (from incomplete combustion), and cyanide poisoning (from burning plastics). All must be considered.\n\nSigns of inhalation injury include facial burns, soot in oropharynx, singed nasal hairs, cough, stridor. High-flow oxygen is essential. Consider early intubation for airway protection.`,
    "Burns + enclosed space fire: assess for inhalation injury, CO poisoning (carboxyhemoglobin), cyanide poisoning. High-flow O2 essential.",
    ["ABA Burn Care Guidelines 2018"],
    "Emergency Medicine",
    "Trauma",
    "hard",
    true,
    "Burns",
    ["inhalation-injury", "resuscitation"],
  ),
  createQuestion(
    'A 25-year-old woman presents with sudden severe headache "worst headache of life" with nausea and photophobia. She is alert and oriented. CT head shows subarachnoid blood. What is the next step?',
    {
      A: "Observation and repeat CT in 24 hours",
      B: "CT angiography or digital subtraction angiography",
      C: "Lumbar puncture",
      D: "Start nimodipine only",
      E: "Conservative management",
    },
    "B",
    `After diagnosing SAH on CT, urgent vascular imaging (CTA or DSA) is needed to identify aneurysm as the cause. This guides definitive treatment (clipping or coiling).\n\nObservation risks rebleeding. LP is contraindicated if CT positive and increased ICP suspected. Nimodipine is started for vasospasm prophylaxis but doesn't replace source control.`,
    "SAH: urgent CTA/DSA to identify aneurysm. Secure aneurysm (clipping/coiling) to prevent rebleed. Nimodipine for vasospasm prophylaxis.",
    ["AHA/ASA Aneurysmal SAH Guidelines 2012"],
    "Emergency Medicine",
    "Neurosurgery",
    "hard",
    true,
    "Subarachnoid Hemorrhage",
    ["aneurysm", "vasospasm"],
  ),
  createQuestion(
    "A 50-year-old man presents with fever 39.5°C, tachycardia, and hypotension 80/50 mmHg. Lactate is 4 mmol/L. He has a suspected urinary source. What is the most appropriate initial management?",
    {
      A: "Wait for blood cultures before antibiotics",
      B: "Broad-spectrum antibiotics within 1 hour + fluid resuscitation + source control",
      C: "Fluid resuscitation only",
      D: "CT abdomen to confirm source",
      E: "Vasopressors first",
    },
    "B",
    `Sepsis with shock requires: empiric broad-spectrum antibiotics within 1 hour, aggressive fluid resuscitation (30 mL/kg crystalloid), and source control. Each hour of delay increases mortality.\n\nAntibiotics should not be delayed for cultures (draw cultures then give antibiotics). Fluids alone insufficient without antibiotics. Imaging can delay treatment. Vasopressors are for persistent hypotension despite adequate fluids.`,
    "Sepsis: antibiotics within 1 hour, 30 mL/kg fluid resuscitation, lactate measurement, blood cultures, source control. Hour-1 bundle.",
    ["Surviving Sepsis Campaign 2021"],
    "Emergency Medicine",
    "Medical Emergencies",
    "medium",
    true,
    "Sepsis",
    ["septic-shock", "bundle"],
  ),
  createQuestion(
    "A 70-year-old woman presents with confusion, ataxia, and ophthalmoplegia (nystagmus and ptosis). She has a history of alcohol abuse and poor nutrition. What is the immediate treatment?",
    {
      A: "Thiamine 100 mg IV before glucose",
      B: "Glucose 50% IV immediately",
      C: "Glucose followed by thiamine",
      D: "Naloxone",
      E: "Flumazenil",
    },
    "A",
    `Wernicke encephalopathy (triad: confusion, ataxia, ophthalmoplegia) requires immediate IV thiamine BEFORE glucose. Glucose without thiamine can worsen Wernicke encephalopathy or precipitate it.\n\nHigh-dose thiamine 200-500 mg IV TDS for 3-5 days, then oral until recovered. Co-administer other B vitamins. Naloxone and flumazenil are for opioid and benzodiazepine overdose respectively.`,
    "Wernicke encephalopathy: give IV thiamine BEFORE glucose in at-risk patients (alcohol, malnutrition). High-dose regimen.",
    ["EFNS Wernicke Encephalopathy Guidelines"],
    "Emergency Medicine",
    "Medical Emergencies",
    "hard",
    true,
    "CNS Infections",
    ["wernicke", "thiamine"],
  ),
];

// ============================================================================
// BASIC SCIENCES - PHARMACOLOGY QUESTIONS (10)
// ============================================================================

export const pharmacologyQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 60-year-old man with atrial fibrillation is started on warfarin. What is the mechanism of action of warfarin?",
    {
      A: "Direct inhibition of thrombin",
      B: "Inhibition of vitamin K epoxide reductase",
      C: "Inhibition of platelet aggregation",
      D: "Activation of antithrombin III",
      E: "Inhibition of factor Xa",
    },
    "B",
    `Warfarin inhibits vitamin K epoxide reductase (VKORC1), preventing the reduction of vitamin K epoxide to active vitamin K. This inhibits the synthesis of vitamin K-dependent clotting factors (II, VII, IX, X, and proteins C and S).\n\nDirect thrombin inhibitors (dabigatran) directly inhibit thrombin. Heparin activates antithrombin III. Factor Xa inhibitors (rivaroxaban, apixaban) directly inhibit factor Xa. Antiplatelets work on platelets.`,
    "Warfarin: vitamin K antagonist. Inhibits synthesis of factors II, VII, IX, X. Slow onset (days). Monitor with INR.",
    ["Goodman & Gilman's Pharmacology, 13th Edition"],
    "Basic Sciences",
    "Pharmacology",
    "easy",
    true,
    "Anticoagulants",
    ["warfarin", "mechanism"],
  ),
  createQuestion(
    "A patient on gentamicin develops renal impairment and ototoxicity. What is the mechanism of aminoglycoside-induced nephrotoxicity?",
    {
      A: "Allergic interstitial nephritis",
      B: "Proximal tubular cell uptake and lysosomal damage",
      C: "Glomerular basement membrane damage",
      D: "Renal vasoconstriction",
      E: "Crystallization in tubules",
    },
    "B",
    `Aminoglycosides are taken up by proximal tubular cells via megalin-cubilin receptor-mediated endocytosis. They accumulate in lysosomes, causing phospholipidosis and tubular cell injury.\n\nAIN is typically drug hypersensitivity (e.g., penicillins, NSAIDs). Glomerular damage causes nephrotic syndrome. Vasoconstriction (NSAIDs, ACE inhibitors) is prerenal. Crystallization occurs with sulfa drugs, acyclovir, methotrexate.`,
    "Aminoglycoside toxicity: dose-related, irreversible uptake by proximal tubule cells. Once-daily dosing reduces toxicity but monitoring levels essential.",
    ["Goodman & Gilman's Pharmacology, 13th Edition"],
    "Basic Sciences",
    "Pharmacology",
    "medium",
    true,
    "Antibiotics",
    ["aminoglycosides", "nephrotoxicity"],
  ),
  createQuestion(
    "A patient with asthma has a prolonged QT interval on ECG after starting antibiotic therapy. Which antibiotic is most likely responsible?",
    {
      A: "Amoxicillin",
      B: "Azithromycin",
      C: "Ciprofloxacin",
      D: "Doxycycline",
      E: "Metronidazole",
    },
    "B",
    `Macrolides (erythromycin, clarithromycin, azithromycin) block IKr potassium channels, prolonging the QT interval and risking torsades de pointes. Risk increases with other QT-prolonging drugs, electrolyte abnormalities, or congenital long QT.\n\nAmoxicillin (penicillin) does not prolong QT. Fluoroquinolones have some QT effect but less than macrolides. Tetracyclines and metronidazole do not significantly prolong QT.`,
    "Macrolides, fluoroquinolones, and some antipsychotics/antidepressants prolong QT. Check ECG and electrolytes in at-risk patients.",
    ["CredibleMeds QT Drug Lists"],
    "Basic Sciences",
    "Pharmacology",
    "medium",
    true,
    "Adverse Drug Reactions",
    ["qt-prolongation", "macrolides"],
  ),
  createQuestion(
    "A patient with depression is started on an SSRI. Which neurotransmitter system is primarily affected?",
    {
      A: "Dopamine",
      B: "Serotonin",
      C: "Norepinephrine",
      D: "GABA",
      E: "Glutamate",
    },
    "B",
    `SSRIs (selective serotonin reuptake inhibitors) selectively inhibit the serotonin transporter (SERT), increasing synaptic serotonin concentrations. This is their primary mechanism of antidepressant effect.\n\nSNRIs affect both serotonin and norepinephrine. TCAs affect multiple neurotransmitters. Dopamine is affected by antipsychotics and stimulants. GABA by benzodiazepines and barbiturates. Glutamate by ketamine (emerging antidepressant).`,
    "SSRIs: selective serotonin reuptake inhibitors. Side effects due to serotonin increase: GI upset, sexual dysfunction, initial anxiety, serotonin syndrome.",
    ["Stahl's Essential Psychopharmacology"],
    "Basic Sciences",
    "Pharmacology",
    "easy",
    true,
    "CNS Drugs",
    ["ssri", "mechanism"],
  ),
  createQuestion(
    "A patient with heart failure is prescribed an ACE inhibitor. What is the mechanism by which ACE inhibitors reduce afterload?",
    {
      A: "Direct arterial vasodilation",
      B: "Inhibition of angiotensin II formation and aldosterone secretion",
      C: "Blockade of angiotensin II receptors",
      D: "Inhibition of bradykinin breakdown",
      E: "Beta-1 receptor blockade",
    },
    "B",
    `ACE inhibitors block the conversion of angiotensin I to angiotensin II. Reduced angiotensin II leads to: arterial and venous vasodilation, reduced aldosterone secretion (less sodium/water retention), and reduced sympathetic activity.\n\nARBs block angiotensin II receptors. Direct vasodilators include nitrates, hydralazine. Bradykinin accumulation causes cough and angioedema (side effects). Beta-blockers work through different mechanism.`,
    "ACE inhibitors: inhibit angiotensin II formation, reduce aldosterone. Benefits in heart failure, hypertension, post-MI, CKD. Side effects: cough, hyperkalemia, angioedema.",
    ["Goodman & Gilman's Pharmacology, 13th Edition"],
    "Basic Sciences",
    "Pharmacology",
    "medium",
    true,
    "Cardiovascular Drugs",
    ["ace-inhibitor", "mechanism"],
  ),
  createQuestion(
    "A patient taking regular paracetamol presents with hepatic failure. What is the mechanism of paracetamol hepatotoxicity?",
    {
      A: "Direct hepatocyte membrane damage",
      B: "Formation of toxic metabolite NAPQI exceeding glutathione stores",
      C: "Mitochondrial DNA damage",
      D: "Bile duct injury",
      E: "Hepatic vein thrombosis",
    },
    "B",
    `Paracetamol is primarily metabolized by glucuronidation and sulfation. A small amount is metabolized by CYP2E1 to NAPQI (N-acetyl-p-benzoquinone imine), a toxic metabolite. Normally detoxified by glutathione, but in overdose, glutathione is depleted, leading to hepatocyte necrosis.\n\nN-acetylcysteine replenishes glutathione stores and binds NAPQI directly. Early treatment (<8 hours) prevents hepatotoxicity.`,
    "Paracetamol toxicity: CYP2E1 metabolizes to NAPQI (toxic). Glutathione depletion in overdose. NAC provides cysteine for glutathione synthesis and directly binds NAPQI.",
    ["Goodman & Gilman's Pharmacology, 13th Edition"],
    "Basic Sciences",
    "Pharmacology",
    "medium",
    true,
    "Adverse Drug Reactions",
    ["paracetamol", "overdose"],
  ),
  createQuestion(
    "A patient on digoxin develops toxicity with nausea, confusion, and ventricular arrhythmias. What is the mechanism of digoxin toxicity?",
    {
      A: "Beta-blockade",
      B: "Inhibition of Na+/K+-ATPase leading to increased intracellular calcium",
      C: "Potassium channel blockade",
      D: "Calcium channel blockade",
      E: "Sodium channel blockade",
    },
    "B",
    `Digoxin inhibits Na+/K+-ATPase, leading to increased intracellular sodium. This reduces the Na+/Ca2+ exchanger activity, causing intracellular calcium accumulation and increased contractility. Toxicity occurs with excessive accumulation.\n\nToxicity is potentiated by hypokalemia (digoxin competes with potassium for Na+/K+-ATPase binding). Treatment includes digoxin-specific antibody fragments (Digibind).`,
    "Digoxin: inhibits Na+/K+-ATPase, increases intracellular Ca2+. Toxicity: GI symptoms, confusion, arrhythmias. Worse with hypokalemia, renal impairment, hypothyroidism.",
    ["Goodman & Gilman's Pharmacology, 13th Edition"],
    "Basic Sciences",
    "Pharmacology",
    "medium",
    true,
    "Cardiovascular Drugs",
    ["digoxin", "toxicity"],
  ),
  createQuestion(
    "A patient with type 2 diabetes is prescribed metformin. What is the primary mechanism of action?",
    {
      A: "Stimulation of insulin secretion from pancreas",
      B: "Activation of AMP-activated protein kinase (AMPK) reducing hepatic gluconeogenesis",
      C: "Inhibition of intestinal glucose absorption",
      D: "Inhibition of DPP-4 enzyme",
      E: "Stimulation of GLP-1 receptors",
    },
    "B",
    `Metformin primarily reduces hepatic glucose production by activating AMPK, which suppresses gluconeogenesis. It also increases peripheral insulin sensitivity and reduces intestinal glucose absorption.\n\nSulfonylureas and meglitinides stimulate insulin secretion. Alpha-glucosidase inhibitors block intestinal glucose absorption. DPP-4 inhibitors block incretin degradation. GLP-1 agonists stimulate GLP-1 receptors.`,
    "Metformin: activates AMPK, reduces hepatic gluconeogenesis. Weight neutral, low hypoglycemia risk. Contraindicated in severe renal impairment (eGFR <30).",
    ["Goodman & Gilman's Pharmacology, 13th Edition"],
    "Basic Sciences",
    "Pharmacology",
    "easy",
    true,
    "Endocrine Drugs",
    ["metformin", "mechanism"],
  ),
  createQuestion(
    "A patient is given atropine for bradycardia. What is the mechanism of action?",
    {
      A: "Beta-1 agonist",
      B: "Muscarinic receptor antagonist",
      C: "Nicotinic receptor antagonist",
      D: "Acetylcholinesterase inhibitor",
      E: "Calcium channel agonist",
    },
    "B",
    `Atropine is a competitive antagonist at muscarinic acetylcholine receptors (M2 in heart). This blocks vagal parasympathetic tone, increasing heart rate.\n\nBeta-1 agonists include dobutamine and isoprenaline. Nicotinic antagonists include neuromuscular blockers. Anticholinesterases include neostigmine. Calcium channel agonists are not commonly used for bradycardia.`,
    "Atropine: muscarinic antagonist. Increases HR by blocking vagal tone. For symptomatic bradycardia. Side effects: dry mouth, urinary retention, confusion.",
    ["Goodman & Gilman's Pharmacology, 13th Edition"],
    "Basic Sciences",
    "Pharmacology",
    "easy",
    true,
    "Autonomic Pharmacology",
    ["atropine", "anticholinergic"],
  ),
  createQuestion(
    "A patient taking simvastatin develops muscle pain and weakness. Creatine kinase is elevated 10 times normal. What is the mechanism of statin-induced myopathy?",
    {
      A: "Direct muscle fiber necrosis",
      B: "Inhibition of HMG-CoA reductase leading to reduced coenzyme Q10 and impaired muscle cell function",
      C: "Immune-mediated muscle destruction",
      D: "Mitochondrial DNA depletion",
      E: "Rhabdomyolysis from direct toxicity",
    },
    "B",
    `Statins inhibit HMG-CoA reductase, blocking cholesterol synthesis. This also reduces synthesis of intermediates including coenzyme Q10 (ubiquinone), which is important for mitochondrial energy production in muscle cells.\n\nThe mechanism is dose-dependent and potentiated by drug interactions (CYP3A4 inhibitors like clarithromycin, azole antifungals, grapefruit), renal impairment, hypothyroidism, and advanced age.`,
    "Statin myopathy: dose-dependent, potentiated by CYP3A4 inhibitors, renal impairment, hypothyroidism. Reduce dose or switch to hydrophilic statin (pravastatin, rosuvastatin).",
    ["Goodman & Gilman's Pharmacology, 13th Edition"],
    "Basic Sciences",
    "Pharmacology",
    "medium",
    true,
    "Adverse Drug Reactions",
    ["statins", "myopathy"],
  ),
];

// Export all additional questions
export const part3Questions = [
  ...surgeryQuestions,
  ...psychiatryQuestions,
  ...emergencyQuestions,
  ...pharmacologyQuestions,
];
