/**
 * Question Bank Seed Data - Part 1
 * Cardiology, Respiratory, Gastroenterology, Nephrology questions
 */

import { IQuestion } from "../types";

const createQuestion = (
  stem: string,
  options: { A: string; B: string; C: string; D: string; E: string },
  correctAnswer: "A" | "B" | "C" | "D" | "E",
  explanation: string,
  teachingPoints: string,
  references: string[],
  subject: string,
  topic: string,
  difficulty: "easy" | "medium" | "hard",
  isHighYield: boolean,
  subtopic?: string,
  tags?: string[],
): Partial<IQuestion> => {
  const answerMap = { A: 0, B: 1, C: 2, D: 3, E: 4 };
  return {
    questionText: stem,
    options: [options.A, options.B, options.C, options.D, options.E],
    correctAnswer: answerMap[correctAnswer],
    explanation,
    category: subject,
    subcategory: subtopic || topic,
    difficulty,
    tags: tags || [],
  };
};

// Cardiology Questions (12)
export const cardiologyQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 67-year-old man presents with sudden onset of severe chest pain radiating to his back. He describes the pain as tearing in nature. His blood pressure is 180/110 mmHg in the right arm and 140/90 mmHg in the left arm. On examination, he has a new neurological deficit in his left leg. What is the most likely diagnosis?",
    {
      A: "Acute myocardial infarction",
      B: "Aortic dissection",
      C: "Pulmonary embolism",
      D: "Pericarditis",
      E: "Esophageal rupture",
    },
    "B",
    "Aortic dissection is the most likely diagnosis given the characteristic features: sudden onset tearing chest pain radiating to the back, blood pressure difference between arms (discrepancy of >20 mmHg), and new neurological deficit indicating involvement of the aortic arch branches. The tearing quality of pain is highly specific for aortic dissection.",
    "Always consider aortic dissection in patients with sudden tearing chest pain, pulse deficits, or neurological symptoms. Blood pressure differences >20 mmHg between arms strongly suggest aortic dissection.",
    ["Davidson Principles and Practice of Medicine, 24th Edition"],
    "Medicine",
    "Cardiology",
    "hard",
    true,
    "Valvular Heart Disease",
    ["emergency", "vascular"],
  ),
  createQuestion(
    "A 55-year-old woman presents with episodes of palpitations, sweating, and anxiety. During an episode, her ECG shows a regular narrow-complex tachycardia at 160 bpm with no visible P waves. Carotid sinus massage terminates the episode. What is the most likely diagnosis?",
    {
      A: "Atrial fibrillation",
      B: "Ventricular tachycardia",
      C: "AV nodal reentrant tachycardia (AVNRT)",
      D: "Atrial flutter",
      E: "Multifocal atrial tachycardia",
    },
    "C",
    "AV nodal reentrant tachycardia (AVNRT) is the most likely diagnosis. Key features: regular narrow-complex tachycardia at 150-250 bpm, absence of visible P waves (retrograde P waves may be buried in QRS), and termination with vagal maneuvers.",
    "Regular narrow-complex tachycardia terminating with vagal maneuvers is AVNRT. Adenosine is the drug of choice if vagal maneuvers fail.",
    ["Harrison Principles of Internal Medicine, 21st Edition"],
    "Medicine",
    "Cardiology",
    "medium",
    true,
    "Arrhythmias",
    ["ecg", "arrhythmia"],
  ),
  createQuestion(
    "A 72-year-old man with chronic heart failure presents with increasing dyspnea and peripheral edema. His medications include ramipril, metoprolol, and furosemide. Examination reveals bilateral basal crackles and elevated JVP. His serum creatinine is 180 micromol/L (baseline 120). Which medication adjustment is most appropriate?",
    {
      A: "Stop the ACE inhibitor",
      B: "Increase the diuretic dose",
      C: "Add digoxin",
      D: "Stop the beta-blocker",
      E: "Add spironolactone",
    },
    "B",
    "Increasing the diuretic dose is most appropriate. The patient has fluid overload signs (dyspnea, edema, crackles, elevated JVP) representing acute heart failure decompensation. The elevated creatinine is likely prerenal azotemia from reduced effective circulating volume.",
    "In acute heart failure decompensation, optimize diuretic therapy first. ACE inhibitors and beta-blockers should generally be continued.",
    ["ESC Guidelines for Heart Failure 2021"],
    "Medicine",
    "Cardiology",
    "medium",
    true,
    "Heart Failure",
    ["heart-failure", "pharmacology"],
  ),
  createQuestion(
    "A 45-year-old man presents with exertional chest pain that resolves with rest. During pain, his ECG shows 2 mm ST-segment depression in leads V4-V6, which normalizes when pain subsides. His troponin levels are normal. What is the most appropriate next step?",
    {
      A: "Immediate thrombolysis",
      B: "Urgent coronary angiography",
      C: "Exercise stress test",
      D: "CT coronary angiography",
      E: "Start aspirin and arrange outpatient review",
    },
    "B",
    "Urgent coronary angiography is indicated. The patient has unstable angina - chest pain with transient ST changes but without elevated troponins. Dynamic ECG changes during symptoms strongly suggest significant coronary artery disease.",
    "Dynamic ECG changes during chest pain indicate unstable angina requiring urgent invasive management. Do not perform stress testing in unstable patients.",
    ["ESC Guidelines for ACS 2023"],
    "Medicine",
    "Cardiology",
    "medium",
    true,
    "Coronary Artery Disease",
    ["acs", "chest-pain"],
  ),
  createQuestion(
    "A 68-year-old woman with rheumatic heart disease presents with dyspnea and orthopnea. On examination, she has a loud first heart sound, an opening snap, and a low-pitched diastolic rumbling murmur at the apex. What is the most likely diagnosis?",
    {
      A: "Aortic stenosis",
      B: "Aortic regurgitation",
      C: "Mitral stenosis",
      D: "Mitral regurgitation",
      E: "Tricuspid regurgitation",
    },
    "C",
    "Mitral stenosis is most likely. Characteristic findings: loud S1, opening snap in early diastole, low-pitched diastolic rumbling murmur at apex. Rheumatic heart disease is strongly associated with mitral stenosis.",
    "Loud S1 + opening snap + diastolic rumbling murmur at apex = mitral stenosis. Always consider rheumatic heart disease as the etiology.",
    ["Talley and OConnor Clinical Examination, 8th Edition"],
    "Medicine",
    "Cardiology",
    "easy",
    true,
    "Valvular Heart Disease",
    ["murmur", "cardiac-exam"],
  ),
  createQuestion(
    "A 35-year-old athlete presents with syncope during exertion. His ECG shows LVH with deep T-wave inversions and prominent Q waves in inferior leads. Echo shows asymmetric septal hypertrophy (25 mm) and systolic anterior motion of the mitral valve. What is the diagnosis?",
    {
      A: "Dilated cardiomyopathy",
      B: "Hypertrophic cardiomyopathy",
      C: "Arrhythmogenic RV cardiomyopathy",
      D: "Athlete heart",
      E: "Aortic stenosis",
    },
    "B",
    "Hypertrophic cardiomyopathy (HCM) is the diagnosis. Key findings: asymmetric septal hypertrophy >15 mm, SAM of mitral valve, exertional syncope. HCM is the most common cause of sudden cardiac death in young athletes.",
    "HCM is the leading cause of sudden cardiac death in young athletes. Asymmetric septal hypertrophy with SAM is diagnostic.",
    ["ESC Guidelines for Cardiomyopathies 2023"],
    "Medicine",
    "Cardiology",
    "medium",
    true,
    "Cardiomyopathies",
    ["sports-medicine", "syncope"],
  ),
  createQuestion(
    "A 58-year-old man presents with acute dyspnea and pleuritic chest pain. He had knee replacement 10 days ago. HR 110 bpm, BP 100/70 mmHg, O2 sat 88 percent on room air. CT pulmonary angiography shows bilateral pulmonary emboli. What is the most appropriate initial management?",
    {
      A: "Start warfarin only",
      B: "Start heparin and warfarin together",
      C: "Systemic thrombolysis",
      D: "Embolectomy",
      E: "Start low molecular weight heparin",
    },
    "E",
    "Starting LMWH is most appropriate. This patient has intermediate-high risk PE with hemodynamic compromise. Immediate priority is anticoagulation with LMWH, unfractionated heparin, or fondaparinux.",
    "In acute PE, start parenteral anticoagulation immediately. LMWH is preferred for most patients.",
    ["ESC Pulmonary Embolism Guidelines 2019"],
    "Medicine",
    "Cardiology",
    "medium",
    true,
    "Pulmonary Embolism",
    ["emergency", "anticoagulation"],
  ),
  createQuestion(
    "A 62-year-old woman presents with fatigue and dyspnea on exertion. ECG shows sinus rhythm with LBBB. Echo shows EF 25 percent, dilated LV, and diffuse hypokinesis. Coronary angiography is normal. What is the most likely diagnosis?",
    {
      A: "Ischemic cardiomyopathy",
      B: "Dilated cardiomyopathy",
      C: "Hypertrophic cardiomyopathy",
      D: "Restrictive cardiomyopathy",
      E: "Arrhythmogenic cardiomyopathy",
    },
    "B",
    "Dilated cardiomyopathy (DCM) is most likely. Features: dilated LV, reduced EF (25 percent), diffuse hypokinesis, normal coronary arteries. LBBB is commonly associated with DCM.",
    "DCM = Dilated LV + Low EF + Diffuse hypokinesis + Normal coronaries.",
    ["ESC Heart Failure Guidelines 2021"],
    "Medicine",
    "Cardiology",
    "medium",
    false,
    "Cardiomyopathies",
    ["echo", "heart-failure"],
  ),
  createQuestion(
    "A 70-year-old man presents with gradual dyspnea and orthopnea. He has a low-volume pulse, harsh crescendo-decrescendo systolic murmur at right upper sternal border radiating to carotids, and delayed carotid upstroke. What is the next investigation?",
    {
      A: "Cardiac catheterization",
      B: "Transthoracic echocardiography",
      C: "Exercise stress testing",
      D: "Cardiac MRI",
      E: "CT coronary angiography",
    },
    "B",
    "TTE is the most appropriate next investigation. Clinical findings (low-volume pulse, harsh systolic murmur radiating to carotids, delayed carotid upstroke) are classic for aortic stenosis. TTE confirms diagnosis and assesses severity.",
    "TTE is first-line for suspected valvular heart disease. In AS, the murmur radiates to carotids and there is a delayed (parvus et tardus) carotid upstroke.",
    ["ACC/AHA Valvular Heart Disease Guidelines 2020"],
    "Medicine",
    "Cardiology",
    "easy",
    true,
    "Valvular Heart Disease",
    ["murmur", "echo"],
  ),
  createQuestion(
    "A 48-year-old man with type 2 diabetes and hypertension has BP 145/92 mmHg. His urine ACR is 45 mg/mmol. Current medications: metformin and amlodipine. Which change is most appropriate?",
    {
      A: "Add atenolol",
      B: "Switch amlodipine to perindopril",
      C: "Add hydrochlorothiazide",
      D: "Add doxazosin",
      E: "Increase amlodipine dose",
    },
    "B",
    "Switching to an ACE inhibitor (perindopril) is most appropriate. This patient has hypertension with albuminuria indicating diabetic kidney disease. ACE inhibitors/ARBs are first-line in diabetes with albuminuria due to renal protection.",
    "In diabetic patients with albuminuria, ACE inhibitors or ARBs are first-line due to renoprotective effects.",
    ["KDIGO Diabetes in CKD Guideline 2022"],
    "Medicine",
    "Cardiology",
    "easy",
    true,
    "Hypertension",
    ["diabetes", "nephrology"],
  ),
  createQuestion(
    "A 65-year-old man presents with chest pain at rest. ECG shows ST elevation in leads II, III, and aVF with reciprocal ST depression in I and aVL. What is the most appropriate immediate management?",
    {
      A: "Aspirin and clopidogrel only",
      B: "Primary PCI within 90 minutes",
      C: "Thrombolysis within 30 minutes",
      D: "Beta-blocker and nitrates",
      E: "CT coronary angiography",
    },
    "B",
    "Primary PCI within 90 minutes is the optimal management for STEMI. This patient has inferior STEMI (ST elevation in II, III, aVF) with reciprocal changes. Primary PCI is superior to thrombolysis when available within acceptable timeframes.",
    "STEMI requires immediate reperfusion. Primary PCI is preferred over thrombolysis when available within 90-120 minutes.",
    ["ESC ACS Guidelines 2023"],
    "Medicine",
    "Cardiology",
    "easy",
    true,
    "Coronary Artery Disease",
    ["stemi", "emergency"],
  ),
  createQuestion(
    "A 52-year-old woman presents with episodic palpitations. ECG during symptoms shows irregularly irregular rhythm with no distinct P waves and fibrillatory waves. The ventricular rate is 120 bpm. What is the most appropriate initial management for rate control?",
    {
      A: "Adenosine",
      B: "Digoxin",
      C: "Beta-blocker or non-DHP calcium channel blocker",
      D: "Amiodarone",
      E: "Atropine",
    },
    "C",
    "Beta-blocker or non-DHP calcium channel blocker (diltiazem or verapamil) is first-line for rate control in acute AF with rapid ventricular response. They slow AV nodal conduction.",
    "In acute AF with rapid ventricular response, beta-blockers or non-dihydropyridine calcium channel blockers are first-line for rate control.",
    ["ESC Atrial Fibrillation Guidelines 2020"],
    "Medicine",
    "Cardiology",
    "easy",
    true,
    "Arrhythmias",
    ["af", "rate-control"],
  ),
];

// Respiratory Questions (10)
export const respiratoryQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 28-year-old woman with asthma presents with worsening shortness of breath and wheeze. RR 28/min, HR 110 bpm, unable to speak in full sentences. PEF is 150 L/min (predicted 450 L/min). What is the most appropriate immediate management?",
    {
      A: "Increase salbutamol inhaler frequency",
      B: "Oral prednisolone and review in 24 hours",
      C: "High-dose inhaled corticosteroids",
      D: "Oxygen, nebulized bronchodilators, and systemic corticosteroids",
      E: "Immediate intubation",
    },
    "D",
    "This patient has acute severe asthma requiring hospital management. PEF 33 percent of predicted indicates severe exacerbation with life-threatening features (inability to complete sentences, RR >25, HR >110).",
    "Acute severe asthma: PEF 33-50 percent predicted. Life-threatening: PEF <33 percent, SpO2 <92 percent, silent chest. Give O2 + nebulized beta-agonists + systemic steroids.",
    ["BTS Asthma Guidelines 2023"],
    "Medicine",
    "Respiratory Medicine",
    "medium",
    true,
    "Asthma",
    ["emergency", "respiratory"],
  ),
  createQuestion(
    "A 68-year-old man with 40 pack-year smoking history presents with progressive dyspnea and chronic productive cough. He has barrel-shaped chest. PFTs show FEV1/FVC 0.62 and FEV1 55 percent predicted. What is the most appropriate pharmacological management?",
    {
      A: "Long-acting bronchodilator only",
      B: "Inhaled corticosteroid only",
      C: "Long-acting bronchodilator plus inhaled corticosteroid",
      D: "Systemic corticosteroids long-term",
      E: "Antibiotics prophylaxis",
    },
    "C",
    "Long-acting bronchodilator plus inhaled corticosteroid is appropriate. This patient has moderate COPD (FEV1 55 percent, FEV1/FVC <0.70). Dual therapy is recommended for moderate symptoms and/or exacerbations.",
    "COPD diagnosis requires FEV1/FVC <0.70 post-bronchodilator. Long-acting bronchodilators are the cornerstone of treatment.",
    ["GOLD COPD Guidelines 2024"],
    "Medicine",
    "Respiratory Medicine",
    "medium",
    true,
    "COPD",
    ["smoking", "pulmonary-function"],
  ),
  createQuestion(
    "A 45-year-old man presents with fever, productive cough, and pleuritic chest pain for 3 days. Examination shows consolidation in the right lower lobe. His CURB-65 score is 1. What is the most appropriate management?",
    {
      A: "Oral amoxicillin and outpatient management",
      B: "IV ceftriaxone and azithromycin",
      C: "Admission for IV antibiotics",
      D: "Oral doxycycline alone",
      E: "Observation without antibiotics",
    },
    "A",
    "Oral amoxicillin and outpatient management is appropriate. CURB-65 score of 1 (confusion, urea >7, RR >30, BP low, age >65) indicates low severity community-acquired pneumonia suitable for outpatient oral antibiotics.",
    "CURB-65 score guides pneumonia severity: 0-1 = outpatient, 2 = consider admission, 3-5 = admit and consider ICU.",
    ["BTS CAP Guidelines 2019"],
    "Medicine",
    "Respiratory Medicine",
    "easy",
    true,
    "Pneumonia",
    ["infectious-disease", "antibiotics"],
  ),
  createQuestion(
    "A 38-year-old woman presents with progressive dyspnea and dry cough. She has digital clubbing and fine bibasal inspiratory crackles. HRCT shows peripheral reticular opacities with traction bronchiectasis and honeycombing at bases. What is the most likely diagnosis?",
    {
      A: "Sarcoidosis",
      B: "Idiopathic pulmonary fibrosis",
      C: "Hypersensitivity pneumonitis",
      D: "Pneumoconiosis",
      E: "Bronchiectasis",
    },
    "B",
    "Idiopathic pulmonary fibrosis (IPF) is most likely. Features: progressive dyspnea, dry cough, clubbing, bibasal crackles, and UIP pattern on HRCT (peripheral reticular opacities, traction bronchiectasis, honeycombing).",
    "IPF presents with progressive dyspnea, clubbing, basal crackles, and UIP pattern on CT (peripheral, basal, subpleural reticulation with honeycombing).",
    ["ATS/ERS IPF Guidelines 2022"],
    "Medicine",
    "Respiratory Medicine",
    "medium",
    true,
    "Interstitial Lung Disease",
    ["ild", "radiology"],
  ),
  createQuestion(
    "A 55-year-old man presents with massive hemoptysis (300 mL in 24 hours). Chest X-ray shows cavitary lesion in the left upper lobe. What is the most appropriate immediate management?",
    {
      A: "Bronchoscopy",
      B: "CT chest",
      C: "Embolization",
      D: "Place bleeding side down and secure airway",
      E: "Start broad-spectrum antibiotics",
    },
    "D",
    "Immediate airway protection with the bleeding lung positioned dependent (down) is the priority. Massive hemoptysis can cause asphyxiation. Securing the airway and protecting the non-bleeding lung is critical before further investigations.",
    "In massive hemoptysis, airway protection is the priority. Position the patient with the bleeding lung down to protect the good lung.",
    ["BTS Hemoptysis Guidelines"],
    "Medicine",
    "Respiratory Medicine",
    "hard",
    true,
    "Respiratory Failure",
    ["emergency", "airway"],
  ),
  createQuestion(
    "A 62-year-old man with COPD presents with worsening dyspnea, increased sputum purulence, and volume. He requires hospital admission. Which organism is most likely responsible?",
    {
      A: "Mycobacterium tuberculosis",
      B: "Streptococcus pneumoniae",
      C: "Haemophilus influenzae",
      D: "Pseudomonas aeruginosa",
      E: "Staphylococcus aureus",
    },
    "C",
    "Haemophilus influenzae is most common in COPD exacerbations requiring hospitalization. Other common pathogens include Streptococcus pneumoniae and Moraxella catarrhalis.",
    "Common organisms in COPD exacerbations: H. influenzae, S. pneumoniae, M. catarrhalis. Pseudomonas in severe disease with risk factors.",
    ["GOLD COPD Guidelines 2024"],
    "Medicine",
    "Respiratory Medicine",
    "medium",
    false,
    "COPD",
    ["exacerbation", "microbiology"],
  ),
  createQuestion(
    "A 35-year-old man presents with sudden onset dyspnea and right-sided pleuritic chest pain. He returned from a long flight 2 days ago. HR 100 bpm, BP 120/80 mmHg, O2 sat 94 percent on room air. Wells score is 4.5. What is the next investigation?",
    {
      A: "D-dimer",
      B: "CT pulmonary angiography",
      C: "Ventilation-perfusion scan",
      D: "Echocardiography",
      E: "Chest X-ray",
    },
    "B",
    "CT pulmonary angiography (CTPA) is the next investigation. Wells score >4 indicates high probability of PE, making D-dimer inappropriate (will be positive). CTPA is the diagnostic test of choice for PE.",
    "In high probability PE (Wells >4), proceed directly to CTPA. D-dimer is only useful for ruling out PE in low probability patients.",
    ["ESC Pulmonary Embolism Guidelines 2019"],
    "Medicine",
    "Respiratory Medicine",
    "easy",
    true,
    "Pulmonary Embolism",
    ["diagnostic"],
  ),
  createQuestion(
    "A 28-year-old woman presents with nasal polyps, asthma, and peripheral blood eosinophilia of 1.8 x 10^9/L. Which medication is most likely to provide benefit?",
    {
      A: "Prednisolone",
      B: "Omalizumab",
      C: "Mepolizumab",
      D: "Montelukast",
      E: "Ipratropium bromide",
    },
    "C",
    "Mepolizumab (anti-IL-5) is most appropriate. This patient has severe eosinophilic asthma with nasal polyps (suggesting aspirin-exacerbated respiratory disease/AERD). Anti-IL-5 biologics target the eosinophilic inflammation.",
    "Severe eosinophilic asthma with nasal polyps responds well to anti-IL-5 biologics (mepolizumab, reslizumab) or anti-IL-5R (benralizumab).",
    ["GINA Severe Asthma Guidelines"],
    "Medicine",
    "Respiratory Medicine",
    "hard",
    false,
    "Asthma",
    ["biologics", "eosinophilic"],
  ),
  createQuestion(
    "A 50-year-old man with sleep apnea is started on CPAP. Which outcome is most likely to improve with effective treatment?",
    {
      A: "Cognitive function",
      B: "Blood pressure control",
      C: "Daytime sleepiness",
      D: "All of the above",
      E: "None of the above",
    },
    "D",
    "All of the listed outcomes improve with effective CPAP therapy. Sleep apnea causes fragmented sleep leading to daytime sleepiness, cognitive impairment, and hypertension. CPAP is first-line treatment that addresses all these issues.",
    "CPAP is first-line treatment for moderate-severe OSA. Benefits include reduced daytime sleepiness, improved cognition, better BP control, and reduced cardiovascular risk.",
    ["AASM OSA Guidelines 2021"],
    "Medicine",
    "Respiratory Medicine",
    "easy",
    false,
    "Sleep Apnea",
    ["cpap", "treatment"],
  ),
  createQuestion(
    "A 42-year-old man presents with cough, fever, and weight loss for 2 months. Chest X-ray shows cavitating lesion in the right upper lobe. Sputum AFB smear is positive. What is the most appropriate initial treatment regimen?",
    {
      A: "Rifampicin and isoniazid for 6 months",
      B: "Rifampicin, isoniazid, pyrazinamide, and ethambutol for 2 months, then rifampicin and isoniazid for 4 months",
      C: "Streptomycin, isoniazid, and rifampicin for 9 months",
      D: "Moxifloxacin and pyrazinamide for 6 months",
      E: "Isoniazid prophylaxis only",
    },
    "B",
    "Standard RIPE regimen (rifampicin, isoniazid, pyrazinamide, ethambutol) for 2 months intensive phase, followed by rifampicin and isoniazid for 4 months continuation phase is standard for drug-susceptible pulmonary TB.",
    "Standard TB treatment: RIPE for 2 months, then rifampicin + isoniazid for 4 months (6 months total for drug-susceptible TB).",
    ["WHO TB Guidelines 2022"],
    "Medicine",
    "Respiratory Medicine",
    "easy",
    true,
    "Tuberculosis",
    ["infectious-disease", "treatment"],
  ),
];

// Export all questions from this file
export const allSeedQuestions: Partial<IQuestion>[] = [
  ...cardiologyQuestions,
  ...respiratoryQuestions,
];
