/**
 * Extended Question Bank Seed Data (Part 2)
 * Additional AMC-style MCQ questions
 */

import { IQuestion } from "../types";

const createQuestion = (
  stem: string,
  options: { A: string; B: string; C: string; D: string; E: string },
  correctAnswer: "A" | "B" | "C" | "D" | "E",
  explanation: string,
  teachingPoints: string,
  references: string[],
  subject: string,
  topic: string,
  difficulty: "easy" | "medium" | "hard",
  isHighYield: boolean,
  subtopic?: string,
  tags?: string[],
): Partial<IQuestion> => {
  const answerMap = { A: 0, B: 1, C: 2, D: 3, E: 4 };
  return {
    questionText: stem,
    options: [options.A, options.B, options.C, options.D, options.E],
    correctAnswer: answerMap[correctAnswer],
    explanation,
    category: subject,
    subcategory: subtopic || topic,
    difficulty,
    tags: tags || [],
  };
};

// ============================================================================
// ENDOCRINOLOGY QUESTIONS (10)
// ============================================================================

export const endocrinologyQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 28-year-old woman presents with tremor, palpitations, heat intolerance, and 5 kg weight loss. She has a smooth goiter and lid lag. TSH is <0.01 mU/L, free T4 is 45 pmol/L. What is the initial treatment?",
    {
      A: "Radioactive iodine",
      B: "Propranolol and carbimazole",
      C: "Subtotal thyroidectomy",
      D: "Lugol iodine",
      E: "Levothyroxine",
    },
    "B",
    `Beta-blocker (propranolol) for symptom control plus antithyroid drug (carbimazole) is the appropriate initial treatment for Graves disease. This treats adrenergic symptoms and reduces thyroid hormone production.\n\nRadioactive iodine may worsen ophthalmopathy. Surgery is second-line. Lugol iodine is pre-operative only. Levothyroxine is for hypothyroidism.`,
    "Graves disease treatment: beta-blockers for symptoms, antithyroid drugs to reduce hormone synthesis. Consider definitive therapy later.",
    ["ATA/AACE Hyperthyroidism Guidelines"],
    "Medicine",
    "Endocrinology",
    "easy",
    true,
    "Thyroid Disorders",
    ["graves", "hyperthyroidism"],
  ),
  createQuestion(
    "A 62-year-old man with type 2 diabetes presents with fasting glucose 12 mmol/L and HbA1c 9.5% on metformin 2g daily. eGFR is 65. What is the most appropriate addition?",
    {
      A: "Gliclazide",
      B: "Empagliflozin",
      C: "Pioglitazone",
      D: "Acarbose",
      E: "NPH insulin",
    },
    "B",
    `SGLT2 inhibitor (empagliflozin) is the preferred add-on to metformin. Benefits: glucose lowering, cardiovascular protection, heart failure benefits, and renal protection.\n\nSulfonylureas cause hypoglycemia and weight gain. Pioglitazone causes weight gain and fluid retention. Acarbose has modest efficacy. Insulin is usually third-line unless very high glucose.`,
    "After metformin, SGLT2 inhibitors or GLP-1 RAs are preferred due to cardiorenal benefits, especially in ASCVD or high-risk patients.",
    ["ADA Standards of Care 2024"],
    "Medicine",
    "Endocrinology",
    "medium",
    true,
    "Diabetes Mellitus",
    ["sglt2", "treatment"],
  ),
  createQuestion(
    "A 35-year-old woman presents with fatigue, weight gain, constipation, and dry skin. TSH is 12 mU/L, free T4 is 10 pmol/L. Anti-TPO antibodies are positive. What is the diagnosis?",
    {
      A: "Subacute thyroiditis",
      B: "Hashimoto thyroiditis",
      C: "Graves disease",
      D: "Iatrogenic hypothyroidism",
      E: "Pituitary dysfunction",
    },
    "B",
    `Hashimoto thyroiditis (chronic autoimmune thyroiditis) is the diagnosis. Features: hypothyroidism, positive TPO antibodies, goiter (often). This is the most common cause of hypothyroidism.\n\nSubacute thyroiditis causes painful thyroid with transient hyperthyroidism. Graves causes hyperthyroidism with TSH receptor antibodies. Iatrogenic would have history of surgery/RAI. Pituitary dysfunction would have inappropriately normal/low TSH.`,
    "Hashimoto thyroiditis = most common cause of hypothyroidism + positive TPO antibodies + goiter.",
    ["ATA Hypothyroidism Guidelines"],
    "Medicine",
    "Endocrinology",
    "easy",
    true,
    "Thyroid Disorders",
    ["hashimoto", "hypothyroidism"],
  ),
  createQuestion(
    "A 50-year-old woman presents with headache, visual field defects, and galactorrhea. Prolactin is 2500 mU/L. MRI shows 2 cm pituitary mass. What is the first-line treatment?",
    {
      A: "Transsphenoidal surgery",
      B: "Cabergoline",
      C: "Bromocriptine",
      D: "Radiotherapy",
      E: "Observation",
    },
    "B",
    `Dopamine agonists (cabergoline preferred over bromocriptine) are first-line for prolactinomas regardless of size. They shrink tumors and normalize prolactin in most patients.\n\nSurgery is reserved for dopamine agonist failure or intolerance. Radiotherapy is for aggressive tumors. Observation is for incidentalomas without endocrine dysfunction.`,
    "Prolactinomas: dopamine agonists (cabergoline first-line) are treatment of choice. Surgery only if medical therapy fails.",
    ["Endocrine Society Prolactinoma Guidelines"],
    "Medicine",
    "Endocrinology",
    "medium",
    true,
    "Pituitary Disorders",
    ["prolactinoma", "medical-therapy"],
  ),
  createQuestion(
    "A 45-year-old man presents with proximal muscle weakness, purple striae, central obesity, and easy bruising. 24-hour urine free cortisol is 450 nmol/day (normal <250). What is the next investigation?",
    {
      A: "Low-dose dexamethasone suppression test",
      B: "ACTH measurement",
      C: "Pituitary MRI",
      D: "Adrenal CT",
      E: "High-dose dexamethasone suppression test",
    },
    "B",
    `ACTH measurement distinguishes ACTH-dependent (pituitary or ectopic) from ACTH-independent (adrenal) Cushing syndrome. This guides subsequent imaging.\n\nLow-dose dexamethasone test confirms diagnosis (already done with elevated UFC). Imaging comes after biochemical characterization. High-dose test helps differentiate pituitary from ectopic ACTH.`,
    "Cushing syndrome workup: confirm hypercortisolism, then measure ACTH to determine ACTH-dependent vs independent, then image appropriately.",
    ["Endocrine Society Cushing Syndrome Guidelines"],
    "Medicine",
    "Endocrinology",
    "medium",
    true,
    "Adrenal Disorders",
    ["cushing", "diagnostic"],
  ),
  createQuestion(
    "A 65-year-old woman presents with back pain and height loss. DEXA scan shows T-score -3.2 at lumbar spine. She had a wrist fracture 2 years ago. What is the first-line treatment?",
    {
      A: "Calcium and vitamin D only",
      B: "Bisphosphonate (alendronate)",
      C: "Denosumab",
      D: "Teriparatide",
      E: "Hormone replacement therapy",
    },
    "B",
    `Bisphosphonates (alendronate) are first-line for osteoporosis. This patient has established osteoporosis (T-score <-2.5) with fragility fracture history.\n\nCalcium and vitamin D are adjunctive. Denosumab is for those intolerant of bisphosphonates or with renal impairment. Teriparatide is for severe osteoporosis. HRT is not first-line in this age group.`,
    "Osteoporosis treatment: bisphosphonates first-line. Ensure calcium and vitamin D sufficiency. Treat for 5 years then reassess.",
    ["AACE Osteoporosis Guidelines 2020"],
    "Medicine",
    "Endocrinology",
    "easy",
    true,
    "Osteoporosis",
    ["fracture", "treatment"],
  ),
  createQuestion(
    "A 28-year-old woman with PCOS is trying to conceive. She has oligomenorrhea and hirsutism. What is the first-line treatment to induce ovulation?",
    {
      A: "Metformin",
      B: "Clomiphene citrate",
      C: "Letrozole",
      D: "In vitro fertilization",
      E: "Spironolactone",
    },
    "C",
    `Letrozole is now first-line for ovulation induction in PCOS. It has higher ovulation and live birth rates than clomiphene with lower multiple pregnancy rates.\n\nMetformin can restore ovulation but less effective. Clomiphene was previously first-line. IVF is for failed ovulation induction. Spironolactone is for hirsutism but contraindicated in pregnancy.`,
    "PCOS infertility: letrozole is first-line for ovulation induction, superior to clomiphene citrate.",
    ["ACOG PCOS Guidelines 2018"],
    "Medicine",
    "Endocrinology",
    "medium",
    true,
    "PCOS",
    ["infertility", "ovulation"],
  ),
  createQuestion(
    "A 40-year-old man presents with severe hypertension (220/130 mmHg), headaches, and sweating. Plasma metanephrines are elevated 4-fold above upper limit of normal. CT shows 4 cm left adrenal mass. What is the definitive treatment?",
    {
      A: "Alpha-blockade then beta-blockade then surgery",
      B: "Immediate laparoscopic adrenalectomy",
      C: "MIBG therapy",
      D: "Chemotherapy",
      E: "Observation with annual imaging",
    },
    "A",
    `Surgical removal after adequate alpha-blockade (phenoxybenzamine) followed by beta-blockade is definitive treatment for pheochromocytoma. Surgery without blockade risks hypertensive crisis.\n\nImmediate surgery is dangerous. MIBG is for metastatic disease. Chemotherapy is for malignant disease. Observation risks hypertensive emergencies.`,
    "Pheochromocytoma: alpha-blockade (2 weeks minimum) then beta-blockade THEN surgery. Never give beta-blocker alone (can cause hypertensive crisis).",
    ["Endocrine Society Pheochromocytoma Guidelines"],
    "Medicine",
    "Endocrinology",
    "hard",
    true,
    "Adrenal Disorders",
    ["pheochromocytoma", "surgery"],
  ),
  createQuestion(
    "A 55-year-old man presents with polyuria (4L/day), polydipsia, and nocturia. Fasting glucose is normal. Serum sodium is 148 mmol/L, urine osmolality 180 mOsm/kg. Water deprivation test shows no increase in urine osmolality, which increases after desmopressin. What is the diagnosis?",
    {
      A: "Primary polydipsia",
      B: "Nephrogenic diabetes insipidus",
      C: "Central diabetes insipidus",
      D: "Diuretic use",
      E: "Osmotic diuresis",
    },
    "C",
    `Central diabetes insipidus is diagnosed by water deprivation test showing failure to concentrate urine that corrects with desmopressin (ADH analog). This indicates deficiency of ADH from posterior pituitary.\n\nPrimary polydipsia would show concentrated urine after water deprivation. Nephrogenic DI does not respond to desmopressin. Diuretics and osmotic diuresis would have different patterns.`,
    "Central DI = no urine concentration with water deprivation + response to desmopressin. Nephrogenic DI = no response to desmopressin.",
    ["Endocrine Society Diabetes Insipidus Guidelines"],
    "Medicine",
    "Endocrinology",
    "hard",
    false,
    "Pituitary Disorders",
    ["di", "water-deprivation"],
  ),
  createQuestion(
    "A 30-year-old woman presents with episodic palpitations, sweating, tremor, and anxiety when fasting. Symptoms resolve with eating. During an episode, glucose is 2.8 mmol/L with simultaneous insulin of 8 mU/L (inappropriately elevated). What is the most likely cause?",
    {
      A: "Insulinoma",
      B: "Reactive hypoglycemia",
      C: "Addison disease",
      D: "Factitious hypoglycemia",
      E: "Non-islet cell tumor hypoglycemia",
    },
    "A",
    `Insulinoma is most likely given Whipple\'s triad: symptoms of hypoglycemia, documented low glucose during symptoms, and relief with glucose. Inappropriately elevated insulin with low glucose confirms inappropriate insulin secretion.\n\nReactive hypoglycemia occurs post-prandially. Addison would cause hyperpigmentation and electrolyte abnormalities. Factitious requires insulin access. Non-islet cell tumors cause hypoglycemia via IGF-2 with suppressed insulin.`,
    "Insulinoma: Whipple's triad (symptoms, low glucose, relief with food) + inappropriate insulin/C-peptide during hypoglycemia.",
    ["Endocrine Society Hypoglycemia Guidelines"],
    "Medicine",
    "Endocrinology",
    "hard",
    true,
    "Hypoglycemia",
    ["whipples-triad", "neuroglycopenic"],
  ),
];

// ============================================================================
// NEUROLOGY QUESTIONS (10)
// ============================================================================

export const neurologyQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 70-year-old man presents with sudden right hemiparesis and aphasia. Last seen well was 3 hours ago. CT shows no hemorrhage but early ischemic changes. BP is 170/95. What is the treatment?",
    {
      A: "Aspirin 300 mg immediately",
      B: "IV alteplase if no contraindications",
      C: "Urgent heparin infusion",
      D: "Blood pressure reduction to <140/90",
      E: "Carotid endarterectomy",
    },
    "B",
    `IV thrombolysis with alteplase is indicated within 4.5 hours for ischemic stroke. BP <185/110 is acceptable. Early ischemic changes are not a contraindication unless extensive.\n\nAspirin is given after thrombolysis or if not eligible. Heparin is not routine in acute stroke. Aggressive BP lowering is contraindicated. Surgery is for secondary prevention.`,
    "Acute ischemic stroke: IV thrombolysis up to 4.5 hours. Door-to-needle time <60 minutes. Check for contraindications.",
    ["AHA/ASA Stroke Guidelines"],
    "Medicine",
    "Neurology",
    "medium",
    true,
    "Stroke",
    ["thrombolysis", "acute"],
  ),
  createQuestion(
    "A 30-year-old woman has two episodes of optic neuritis (right then left) and one episode of transverse myelitis over 2 years. MRI shows longitudinally extensive spinal cord lesions. Aquaporin-4 antibodies are positive. What is the diagnosis?",
    {
      A: "Multiple sclerosis",
      B: "Neuromyelitis optica",
      C: "Acute disseminated encephalomyelitis",
      D: "Sarcoidosis",
      E: "Systemic lupus erythematosus",
    },
    "B",
    `Neuromyelitis optica (Devic disease) is characterized by recurrent optic neuritis and longitudinally extensive transverse myelitis with positive AQP4 antibodies. Different from MS by clinical and MRI features.\n\nMS lesions are ovoid, periventricular, and spinal lesions are usually <3 segments. ADEM is monophasic. Sarcoidosis and SLE have different patterns and associated features.`,
    "NMO = optic neuritis + myelitis + AQP4 antibodies. Longitudinally extensive spinal lesions (>3 segments) distinguish from MS.",
    ["International Consensus Diagnostic Criteria for NMO 2015"],
    "Medicine",
    "Neurology",
    "medium",
    true,
    "Multiple Sclerosis",
    ["nmo", "aquaporin-4"],
  ),
  createQuestion(
    "A 65-year-old man presents with resting tremor, bradykinesia, rigidity, and postural instability. He responds well to levodopa. What is the most likely diagnosis?",
    {
      A: "Essential tremor",
      B: "Parkinson disease",
      C: "Progressive supranuclear palsy",
      D: "Multiple system atrophy",
      E: "Lewy body dementia",
    },
    "B",
    `Parkinson disease is most likely given the classic TRAP symptoms (Tremor, Rigidity, Akinesia/Bradykinesia, Postural Instability) and good response to levodopa. Asymmetric onset is typical.\n\nEssential tremor is action tremor without other features. PSP has vertical gaze palsy and early falls. MSA has autonomic dysfunction. LBD has early cognitive impairment and visual hallucinations.`,
    "Parkinson disease: TRAP symptoms (Tremor, Rigidity, Akinesia, Postural Instability), asymmetric onset, good levodopa response.",
    ["MDS Clinical Diagnostic Criteria for Parkinson Disease"],
    "Medicine",
    "Neurology",
    "easy",
    true,
    "Parkinson Disease",
    ["trap", "levodopa"],
  ),
  createQuestion(
    "A 25-year-old woman presents with severe throbbing headache, nausea, photophobia, and phonophobia. Headache is unilateral and pulsating, lasting 24-72 hours. She has similar episodes monthly. What is first-line acute treatment?",
    {
      A: "Propranolol",
      B: "Sumatriptan",
      C: "Sodium valproate",
      D: "Amitriptyline",
      E: "Topiramate",
    },
    "B",
    `Sumatriptan (triptan) is first-line acute treatment for moderate-severe migraine. This patient has typical migraine without aura. Triptans are most effective when taken early.\n\nPropranolol, valproate, amitriptyline, and topiramate are preventive medications, not acute treatments. Simple analgesics are first-line for mild attacks.`,
    "Acute migraine treatment: triptans for moderate-severe attacks, simple analgesics + antiemetic for mild attacks. Preventive therapy if >4 attacks/month.",
    ["Headache Classification ICHD-3", "AHS Migraine Guidelines"],
    "Medicine",
    "Neurology",
    "easy",
    true,
    "Headache",
    ["migraine", "acute-treatment"],
  ),
  createQuestion(
    "A 40-year-old man presents with progressive weakness starting in legs and ascending over 2 weeks. He had diarrhea 3 weeks ago. Examination shows areflexia and weakness. Nerve conduction studies show demyelination. CSF shows albuminocytologic dissociation. What is the diagnosis?",
    {
      A: "Chronic inflammatory demyelinating polyneuropathy",
      B: "Guillain-Barre syndrome",
      C: "Myasthenia gravis",
      D: "Motor neuron disease",
      E: "Lambert-Eaton syndrome",
    },
    "B",
    `Guillain-Barre syndrome is characterized by acute/subacute ascending paralysis, areflexia, antecedent infection (Campylobacter), demyelinating features on NCS, and albuminocytologic dissociation in CSF (high protein, normal cells).\n\nCIDP has progressive course >8 weeks. MG has fatigable weakness with preserved reflexes. MND has UMN and LMN signs. LEMS has presynaptic defect and autonomic features.`,
    "GBS = ascending paralysis + areflexia + antecedent infection + demyelination + albuminocytologic dissociation. Monitor respiratory function.",
    ["EFNS/PNS GBS Guidelines"],
    "Medicine",
    "Neurology",
    "medium",
    true,
    "Guillain-Barre Syndrome",
    ["ascending-paralysis", "plasmapheresis"],
  ),
  createQuestion(
    "A 28-year-old woman presents with episodic diplopia, ptosis, and limb weakness that worsens with activity and improves with rest. Edrophonium test is positive. Acetylcholine receptor antibodies are positive. What is the first-line treatment?",
    {
      A: "Pyridostigmine",
      B: "Prednisolone",
      C: "Plasmapheresis",
      D: "Thymectomy",
      E: "Azathioprine",
    },
    "A",
    `Pyridostigmine (acetylcholinesterase inhibitor) is first-line symptomatic treatment for MG. It improves neuromuscular transmission. Immunosuppression is added for inadequate control.\n\nSteroids are for immunosuppression but can cause initial worsening. Plasmapheresis is for crisis. Thymectomy is for thymomatous or non-thymomatous generalized MG. Azathioprine is steroid-sparing.`,
    "MG treatment: pyridostigmine first-line for symptoms. Add immunosuppression if inadequate. Thymectomy for appropriate patients.",
    ["MGFA Myasthenia Gravis Guidelines"],
    "Medicine",
    "Neurology",
    "easy",
    true,
    "Myasthenia Gravis",
    ["edrophonium", "acetylcholine"],
  ),
  createQuestion(
    "A 60-year-old man presents with rapidly progressive dementia, myoclonus, and ataxia over 3 months. EEG shows periodic sharp wave complexes. CSF is normal. What is the most likely diagnosis?",
    {
      A: "Alzheimer disease",
      B: "Creutzfeldt-Jakob disease",
      C: "Lewy body dementia",
      D: "Vascular dementia",
      E: "Normal pressure hydrocephalus",
    },
    "B",
    `Creutzfeldt-Jakob disease presents with rapidly progressive dementia, myoclonus, ataxia, visual disturbances, and characteristic EEG findings (periodic sharp wave complexes).\n\nAlzheimer disease is slowly progressive without myoclonus early. LBD has visual hallucinations and parkinsonism. Vascular dementia has stepwise decline. NPH has gait apraxia, incontinence, and dementia.`,
    "CJD = rapidly progressive dementia + myoclonus + EEG periodic sharp waves. 14-3-3 protein and RT-QuIC support diagnosis.",
    ["WHO CJD Diagnostic Criteria"],
    "Medicine",
    "Neurology",
    "hard",
    false,
    "Dementia",
    ["prion", "rapid-dementia"],
  ),
  createQuestion(
    "A 35-year-old man presents with severe headache, meningismus, and photophobia. LP shows opening pressure 25 cm H2O, cloudy CSF with WBC 2000 (neutrophils), protein 2 g/L, glucose 1.5 mmol/L (serum 5). What is the most likely organism?",
    {
      A: "Streptococcus pneumoniae",
      B: "Neisseria meningitidis",
      C: "Listeria monocytogenes",
      D: "Herpes simplex virus",
      E: "Mycobacterium tuberculosis",
    },
    "A",
    `S. pneumoniae is the most common cause of bacterial meningitis in adults. CSF shows typical bacterial pattern: neutrophilic pleocytosis, low glucose, high protein. This patient\'s age favors pneumococcus.\n\nMeningococcus is more common in younger patients. Listeria affects neonates, elderly, and immunocompromised. Viral meningitis has lymphocytes. TB has lymphocytes and very low glucose.`,
    "Bacterial meningitis: empirical antibiotics after blood cultures (ceftriaxone + vancomycin ± ampicillin). LP first unless contraindicated.",
    ["IDSA Bacterial Meningitis Guidelines 2004"],
    "Medicine",
    "Neurology",
    "medium",
    true,
    "Meningitis",
    ["csf", "empiric-antibiotics"],
  ),
  createQuestion(
    "A 50-year-old woman presents with recurrent episodes of vertigo lasting 20-30 minutes, associated with tinnitus and fluctuating hearing loss. What is the most likely diagnosis?",
    {
      A: "Benign paroxysmal positional vertigo",
      B: "Vestibular migraine",
      C: "Meniere disease",
      D: "Vestibular neuritis",
      E: "Acoustic neuroma",
    },
    "C",
    `Meniere disease is characterized by episodic vertigo (20 min-12 hours), fluctuating sensorineural hearing loss, tinnitus, and aural fullness. This classic tetrad distinguishes it from other causes.\n\nBPPV has brief positional vertigo without hearing loss. Vestibular migraine has headache and longer duration. Vestibular neuritis has persistent vertigo without hearing loss. Acoustic neuroma causes progressive unilateral hearing loss.`,
    "Meniere disease: tetrad of episodic vertigo + fluctuating hearing loss + tinnitus + aural fullness. Duration 20 minutes to 12 hours.",
    ["AAO-HNS Meniere Disease Guidelines"],
    "Medicine",
    "Neurology",
    "medium",
    false,
    "Vertigo",
    ["meniere", "hearing-loss"],
  ),
  createQuestion(
    "A 65-year-old woman presents with severe left-sided facial pain in the distribution of the maxillary division of trigeminal nerve. Pain is sharp, electric-shock like, lasting seconds, triggered by touch or chewing. MRI is normal. What is the first-line treatment?",
    {
      A: "Sumatriptan",
      B: "Carbamazepine",
      C: "Amitriptyline",
      D: "Gabapentin",
      E: "Surgical microvascular decompression",
    },
    "B",
    `Carbamazepine (or oxcarbazepine) is first-line medical treatment for trigeminal neuralgia. It is highly effective in most patients.\n\nSumatriptan is for migraine. Amitriptyline and gabapentin are second-line. Surgery is for refractory cases or when medications fail.`,
    "Trigeminal neuralgia: carbamazepine first-line. Surgery (MVD or rhizotomy) for refractory cases. Distinguish from secondary causes.",
    ["AAN Trigeminal Neuralgia Guidelines 2008"],
    "Medicine",
    "Neurology",
    "medium",
    true,
    "Neuropathy",
    ["trigeminal", "neuralgia"],
  ),
];

// ============================================================================
// OBSTETRICS & GYNECOLOGY QUESTIONS (12)
// ============================================================================

export const obgynQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 28-year-old woman at 32 weeks gestation presents with severe headache, visual disturbances, and right upper quadrant pain. BP is 160/110 mmHg, proteinuria 3+. What is the most appropriate immediate management?",
    {
      A: "Oral methyldopa",
      B: "IV magnesium sulfate and controlled delivery",
      C: "Oral labetalol and observation",
      D: "Aspirin 150 mg",
      E: "Emergency cesarean section",
    },
    "B",
    `This is severe pre-eclampsia at 32 weeks. Management includes: IV magnesium sulfate for seizure prophylaxis, controlled BP, corticosteroids for fetal lung maturity, and delivery once stable.\n\nOral medications are insufficient for severe features. Aspirin is for prevention, not treatment. Emergency C-section may not be needed if stable and steroids can be given.`,
    "Severe pre-eclampsia: magnesium sulfate, control BP <160/110, deliver after stabilization. Steroids if <34 weeks.",
    ["ACOG Pre-eclampsia Guidelines 2020"],
    "Obstetrics & Gynecology",
    "Obstetrics",
    "medium",
    true,
    "Hypertensive Disorders",
    ["pre-eclampsia", "magnesium"],
  ),
  createQuestion(
    "A 26-year-old woman at 38 weeks gestation presents with decreased fetal movements. CTG shows reduced variability and late decelerations. What is the most appropriate management?",
    {
      A: "Continue monitoring and await spontaneous labor",
      B: "Amnioinfusion",
      C: "Immediate delivery",
      D: "Oxytocin augmentation",
      E: "Tocolysis",
    },
    "C",
    `Immediate delivery is indicated for fetal compromise (reduced variability + late decelerations = non-reassuring CTG). At 38 weeks, the fetus is mature and delivery is safer than expectant management.\n\nContinued monitoring risks fetal death. Amnioinfusion is for variable decelerations due to oligohydramnios. Augmentation is inappropriate. Tocolysis is contraindicated.`,
    "Non-reassuring CTG with reduced variability and late decelerations requires immediate delivery if fetal compromise suspected.",
    ["RCOG Fetal Monitoring Guidelines"],
    "Obstetrics & Gynecology",
    "Obstetrics",
    "medium",
    true,
    "Antenatal Care",
    ["ctg", "fetal-distress"],
  ),
  createQuestion(
    "A 30-year-old woman presents with secondary amenorrhea for 6 months. She has galactorrhea. Prolactin is elevated at 1200 mU/L. Pregnancy test is negative. MRI shows microprolactinoma. What is the treatment?",
    {
      A: "Transsphenoidal surgery",
      B: "Cabergoline",
      C: "Radiation therapy",
      D: "Observation",
      E: "Bromocriptine if planning pregnancy",
    },
    "B",
    `Dopamine agonists (cabergoline preferred) are first-line for prolactinomas regardless of size or fertility desires. They normalize prolactin and reduce tumor size.\n\nSurgery is for dopamine agonist failure. Radiation is rare. Observation risks tumor growth and bone loss from hypoestrogenism. Cabergoline is safe in pregnancy.`,
    "Prolactinoma: dopamine agonists first-line. Cabergoline preferred due to better efficacy and tolerability than bromocriptine.",
    ["Endocrine Society Prolactinoma Guidelines"],
    "Obstetrics & Gynecology",
    "Gynecology",
    "medium",
    true,
    "Menstrual Disorders",
    ["prolactinoma", "amenorrhea"],
  ),
  createQuestion(
    "A 35-year-old woman presents with heavy menstrual bleeding and dysmenorrhea. Pelvic ultrasound shows multiple uterine fibroids, the largest 5 cm. She wishes to preserve fertility. What is the first-line treatment?",
    {
      A: "Hysterectomy",
      B: "GnRH agonist",
      C: "Levonorgestrel IUD",
      D: "Uterine artery embolization",
      E: "Myomectomy",
    },
    "C",
    `Levonorgestrel IUD is first-line for heavy menstrual bleeding with fibroids, especially when fertility preservation is desired. It significantly reduces bleeding.\n\nHysterectomy is definitive but not fertility-preserving. GnRH agonists are temporary. UAE and myomectomy are options but IUD is less invasive first-line.`,
    "Heavy menstrual bleeding with fibroids: LNG-IUD first-line if fertility desired. Myomectomy or UAE if IUD fails or anatomically unsuitable.",
    ["NICE Heavy Menstrual Bleeding Guidelines"],
    "Obstetrics & Gynecology",
    "Gynecology",
    "easy",
    true,
    "Uterine Fibroids",
    ["fibroids", "menorrhagia"],
  ),
  createQuestion(
    "A 24-year-old woman presents with lower abdominal pain, fever, and purulent vaginal discharge. She has cervical motion tenderness and adnexal tenderness. What is the most appropriate antibiotic regimen?",
    {
      A: "Oral amoxicillin",
      B: "Ceftriaxone IM plus doxycycline plus metronidazole",
      C: "Oral metronidazole alone",
      D: "Azithromycin single dose",
      E: "Ciprofloxacin",
    },
    "B",
    `Ceftriaxone (covers gonorrhea) plus doxycycline (covers chlamydia) plus metronidazole (covers anaerobes) is the recommended empiric regimen for PID.\n\nSingle agents are inadequate for polymicrobial infection. Outpatient treatment is appropriate for mild-moderate disease. Inpatient IV therapy for severe disease.`,
    "PID treatment: ceftriaxone + doxycycline + metronidazole. Covers gonorrhea, chlamydia, and anaerobes. Treat partners.",
    ["CDC STI Guidelines 2021"],
    "Obstetrics & Gynecology",
    "Gynecology",
    "medium",
    true,
    "Pelvic Inflammatory Disease",
    ["pid", "antibiotics"],
  ),
  createQuestion(
    "A 32-year-old woman at 28 weeks gestation has a glucose challenge test of 10.2 mmol/L at 2 hours. What is the next step in management?",
    {
      A: "Start insulin therapy",
      B: "Start metformin",
      C: "Dietary modification and glucose monitoring",
      D: "Oral glucose tolerance test",
      E: "Start glyburide",
    },
    "C",
    `One elevated value on GTT (if diagnostic OGTT performed) or GCT > threshold requires dietary counseling, glucose monitoring, and lifestyle modification. Many women achieve glycemic control with diet alone.\n\nMedications (insulin, metformin) are added if dietary measures fail. OGTT not needed if GTT already diagnostic.`,
    "GDM management: dietary modification and glucose monitoring first. Add insulin if targets not met. Metformin or glyburide if insulin declined.",
    ["ADIPS GDM Guidelines 2020"],
    "Obstetrics & Gynecology",
    "Obstetrics",
    "easy",
    true,
    "Gestational Diabetes",
    ["gdm", "management"],
  ),
  createQuestion(
    "A 29-year-old woman at 41 weeks gestation undergoes induction of labor. After 12 hours, she is fully dilated and has been pushing for 2 hours. Fetal head is at +1 station, occiput posterior position. CTG is reassuring. What is the next step?",
    {
      A: "Continue pushing for another hour",
      B: "Vacuum-assisted delivery",
      C: "Emergency cesarean section",
      D: "Manual rotation and/or operative delivery",
      E: "Oxytocin augmentation",
    },
    "D",
    `Manual rotation to occiput anterior or operative vaginal delivery (forceps/vacuum) is appropriate for prolonged second stage with OP position. This can avoid cesarean section.\n\nContinued pushing without progress is not appropriate. Vacuum alone in OP position is less successful. C-section is last resort. Augmentation is contraindicated in second stage.`,
    "Prolonged second stage: consider manual rotation for OP position, operative vaginal delivery, or cesarean if unsuccessful.",
    ["RCOG Operative Vaginal Delivery Guidelines"],
    "Obstetrics & Gynecology",
    "Obstetrics",
    "hard",
    false,
    "Labor and Delivery",
    ["prolonged-second-stage", "operative-delivery"],
  ),
  createQuestion(
    "A 45-year-old woman presents with irregular menstrual bleeding. Endometrial biopsy shows complex atypical hyperplasia. What is the recommended treatment?",
    {
      A: "Oral progesterone",
      B: "Levonorgestrel IUD",
      C: "Total hysterectomy",
      D: "Observation",
      E: "Tamoxifen",
    },
    "C",
    `Hysterectomy is recommended for complex atypical hyperplasia due to high risk (30-50%) of concurrent endometrial cancer or progression to cancer. This is especially true in perimenopausal women.\n\nProgesterone therapy (oral or LNG-IUD) is for fertility preservation or surgical contraindications. Observation is inappropriate. Tamoxifen increases endometrial cancer risk.`,
    "Complex atypical endometrial hyperplasia: hysterectomy recommended (high cancer risk). Fertility-sparing progesterone for select patients.",
    ["ESGO Endometrial Cancer Guidelines"],
    "Obstetrics & Gynecology",
    "Gynecology",
    "medium",
    true,
    "Endometrial Cancer",
    ["hyperplasia", "hysterectomy"],
  ),
  createQuestion(
    "A 25-year-old woman presents with severe pelvic pain and a 6 cm ovarian cyst on ultrasound. The cyst has solid components and papillary projections. CA-125 is 200 U/mL. What is the most appropriate management?",
    {
      A: "Oral contraceptives and repeat ultrasound in 3 months",
      B: "Laparoscopic cystectomy",
      C: "Exploratory laparotomy with surgical staging",
      D: "Chemotherapy",
      E: "Aspiration of cyst",
    },
    "C",
    `Surgical exploration with staging is indicated for complex ovarian masses with solid components, papillary projections, and elevated tumor markers in young women. This may be early-stage ovarian cancer.\n\nObservation is inappropriate given suspicious features. Cystectomy without staging is inadequate if malignancy suspected. Chemotherapy comes after surgery and staging. Aspiration risks spillage.`,
    "Suspicious ovarian mass (solid components, papillary projections, elevated markers): surgical staging required. Fertility-sparing surgery if early stage and fertility desired.",
    ["ESGO Ovarian Cancer Guidelines"],
    "Obstetrics & Gynecology",
    "Gynecology",
    "hard",
    true,
    "Ovarian Cancer",
    ["adnexal-mass", "staging"],
  ),
  createQuestion(
    "A 30-year-old woman presents with primary infertility for 2 years. She has irregular cycles and hirsutism. Ultrasound shows polycystic ovaries. What is the first-line treatment to induce ovulation?",
    {
      A: "In vitro fertilization",
      B: "Clomiphene citrate",
      C: "Letrozole",
      D: "Metformin",
      E: "Gonadotropins",
    },
    "C",
    `Letrozole is now first-line for ovulation induction in PCOS due to higher ovulation and live birth rates than clomiphene citrate.\n\nIVF is for failed ovulation induction. Clomiphene was previously first-line. Metformin can restore ovulation but is less effective. Gonadotropins are second-line due to higher multiple pregnancy risk.`,
    "PCOS infertility: letrozole first-line for ovulation induction. Metformin can help ovulation but less effective.",
    ["ACOG PCOS Guidelines"],
    "Obstetrics & Gynecology",
    "Gynecology",
    "medium",
    true,
    "PCOS",
    ["infertility", "ovulation-induction"],
  ),
  createQuestion(
    "A 35-year-old woman at 20 weeks gestation presents with painless vaginal bleeding. Ultrasound shows placenta previa with placental edge 1 cm from internal os. What is the management?",
    {
      A: "Digital vaginal examination",
      B: "Speculum examination",
      C: "Expectant management with pelvic rest",
      D: "Emergency cesarean section",
      E: "Induction of labor",
    },
    "C",
    `Expectant management with pelvic rest is appropriate for asymptomatic or mild bleeding placenta previa. Most previas diagnosed at 20 weeks will resolve as uterus grows.\n\nDigital examination is contraindained (risk of hemorrhage). Speculum examination can be done carefully if needed. Delivery is indicated only for heavy bleeding or at term if persistent previa.`,
    "Placenta previa: expectant management if asymptomatic/mild bleeding. Pelvic rest. C-section if persistent at term or heavy bleeding.",
    ["RCOG Placenta Praevia Guidelines"],
    "Obstetrics & Gynecology",
    "Obstetrics",
    "medium",
    true,
    "Antepartum Hemorrhage",
    ["placenta-previa", "expectant-management"],
  ),
  createQuestion(
    "A 28-year-old woman develops fever and uterine tenderness on day 3 postpartum. She had prolonged rupture of membranes and chorioamnionitis during labor. What is the most likely diagnosis and treatment?",
    {
      A: "Endometritis; ampicillin, gentamicin, and metronidazole",
      B: "Wound infection; oral antibiotics",
      C: "Mastitis; flucloxacillin",
      D: "Urinary tract infection; trimethoprim",
      E: "DVT; enoxaparin",
    },
    "A",
    `Postpartum endometritis is most likely given risk factors (prolonged ROM, chorioamnionitis) and presentation (fever, uterine tenderness). Treatment is broad-spectrum antibiotics covering gram-positives, gram-negatives, and anaerobes.\n\nOther diagnoses are less likely given uterine tenderness. C-section is a major risk factor but vaginal delivery with chorioamnionitis also increases risk.`,
    "Postpartum endometritis: fever + uterine tenderness + risk factors. Treat with broad-spectrum antibiotics (ampicillin, gentamicin, metronidazole/clindamycin).",
    ["ACOG Postpartum Endometritis Guidelines"],
    "Obstetrics & Gynecology",
    "Obstetrics",
    "medium",
    false,
    "Postpartum Care",
    ["endometritis", "postpartum-infection"],
  ),
];

// ============================================================================
// PEDIATRICS QUESTIONS (8)
// ============================================================================

export const pediatricsQuestions: Partial<IQuestion>[] = [
  createQuestion(
    "A 3-day-old term infant develops jaundice. Bilirubin is 280 μmol/L at 48 hours. Blood group is A positive, mother is O positive. Coombs test is positive. What is the most likely diagnosis?",
    {
      A: "Physiological jaundice",
      B: "ABO incompatibility hemolytic disease",
      C: "Rh hemolytic disease",
      D: "G6PD deficiency",
      E: "Biliary atresia",
    },
    "B",
    `ABO incompatibility is most likely: mother O (anti-A and anti-B antibodies), baby A, positive Coombs, early jaundice. This is the most common cause of hemolytic disease despite Rh compatibility.\n\nPhysiological jaundice is milder and later. Rh disease requires Rh-negative mother. G6PD would not have positive Coombs. Biliary atresia presents with conjugated hyperbilirubinemia and acholic stools.`,
    "ABO incompatibility: mother O, baby A or B, positive direct Coombs, early hemolysis. Most common cause of hemolytic jaundice.",
    ["AAP Neonatal Jaundice Guidelines 2022"],
    "Pediatrics",
    "Neonatology",
    "medium",
    true,
    "Neonatal Jaundice",
    ["hemolysis", "phototherapy"],
  ),
  createQuestion(
    "A 6-month-old infant presents with cough, coryza, fever, and tachypnea. On examination, there is wheezing and crackles. Chest X-ray shows hyperinflation and peribronchial cuffing. What is the most likely causative organism?",
    {
      A: "Streptococcus pneumoniae",
      B: "Respiratory syncytial virus",
      C: "Bordetella pertussis",
      D: "Haemophilus influenzae",
      E: "Chlamydia trachomatis",
    },
    "B",
    `RSV is the most common cause of bronchiolitis in infants, presenting with cough, coryza, fever, wheezing, and hyperinflation on CXR during winter epidemics.\n\nPneumococcus and H. influenzae cause bacterial pneumonia with consolidation. Pertussis causes paroxysmal cough without fever. Chlamydia causes afebrile pneumonia with staccato cough in young infants.`,
    "Bronchiolitis: RSV most common cause in infants <1 year. Supportive care. Consider hospitalization if respiratory distress, hypoxia, or poor feeding.",
    ["AAP Bronchiolitis Guidelines 2014"],
    "Pediatrics",
    "Pediatric Medicine",
    "easy",
    true,
    "Respiratory Infections",
    ["rsv", "bronchiolitis"],
  ),
  createQuestion(
    "A 2-year-old child presents with sudden onset of barking cough, stridor, and hoarseness. Symptoms are worse at night. The child has low-grade fever and appears well between coughing episodes. What is the most appropriate management?",
    {
      A: "Immediate intubation",
      B: "Nebulized adrenaline and oral dexamethasone",
      C: "Antibiotics",
      D: "Chest X-ray",
      E: "Nebulized salbutamol",
    },
    "B",
    `Croup (laryngotracheobronchitis) is the diagnosis. Mild-moderate croup is managed with oral dexamethasone (single dose). Nebulized adrenaline is for moderate-severe croup with stridor at rest.\n\nIntubation is rarely needed. Antibiotics are not indicated (viral cause). CXR not routinely needed. Salbutamol is not effective for croup.`,
    "Croup: barking cough, stridor, hoarseness. Treat with single dose oral dexamethasone. Adrenaline for moderate-severe cases.",
    ["NICE Croup Guidelines"],
    "Pediatrics",
    "Pediatric Emergencies",
    "easy",
    true,
    "Acute Asthma",
    ["croup", "stridor"],
  ),
  createQuestion(
    "An 18-month-old child presents with fever for 5 days, bilateral conjunctival injection, strawberry tongue, erythematous rash, and swollen extremities. What is the most appropriate treatment?",
    {
      A: "Supportive care only",
      B: "IVIG 2 g/kg and aspirin",
      C: "Antibiotics",
      D: "Corticosteroids",
      E: "Aspirin alone",
    },
    "B",
    `Kawasaki disease is the diagnosis. Standard treatment is IVIG 2 g/kg single infusion plus aspirin (high dose initially, then low dose). This reduces coronary artery aneurysm risk.\n\nSupportive care alone risks coronary complications. Antibiotics are not indicated. Steroids are reserved for IVIG-resistant cases. Aspirin alone is insufficient.`,
    "Kawasaki disease: IVIG 2 g/kg + aspirin reduces coronary artery aneurysm risk. Treat within 10 days of fever onset.",
    ["AHA Kawasaki Disease Guidelines 2017"],
    "Pediatrics",
    "Pediatric Medicine",
    "medium",
    true,
    "Pediatric Rash",
    ["kawasaki", "ivig"],
  ),
  createQuestion(
    "A 9-month-old infant presents with vomiting, diarrhea, and poor feeding for 2 days. On examination, the infant is lethargic with sunken fontanelle, dry mucous membranes, and capillary refill 3 seconds. Weight has decreased from 9 kg to 8.2 kg. What is the degree of dehydration?",
    {
      A: "No dehydration",
      B: "Mild dehydration (3-5%)",
      C: "Moderate dehydration (6-9%)",
      D: "Severe dehydration (>10%)",
      E: "Shock",
    },
    "C",
    `Moderate dehydration (6-9%): weight loss ~9%, sunken fontanelle, dry mucous membranes, lethargy, decreased skin turgor, delayed capillary refill (2-4 seconds).\n\nNo dehydration: normal examination. Mild: minimal signs. Severe/shock: altered consciousness, prolonged capillary refill (>4 sec), tachycardia, hypotension.`,
    "Dehydration assessment: weight loss %, clinical signs (fontanelle, mucous membranes, capillary refill, mental status).",
    ["WHO Diarrhoea Guidelines", "NICE Dehydration Guidelines"],
    "Pediatrics",
    "Pediatric Medicine",
    "easy",
    true,
    "Diarrhea and Dehydration",
    ["gastroenteritis", "rehydration"],
  ),
  createQuestion(
    "A 4-year-old child presents with sudden onset of limping and refusal to bear weight on the right leg. There is no history of trauma. On examination, the right hip is held in flexion, abduction, and external rotation. What is the most likely diagnosis?",
    {
      A: "Developmental dysplasia of the hip",
      B: "Transient synovitis",
      C: "Septic arthritis",
      D: "Perthes disease",
      E: "Slipped capital femoral epiphysis",
    },
    "C",
    `Septic arthritis is the most important diagnosis to exclude. The child holds the hip in the position of maximum joint capacity (flexion, abduction, external rotation) to minimize intra-articular pressure.\n\nDDH presents in infancy. Transient synovitis usually follows viral illness and child can bear some weight. Perthes affects 4-8 years but has insidious onset. SCFE affects adolescents.`,
    "Acute hip pain with refusal to weight bear: septic arthritis must be excluded urgently. Joint aspiration for diagnosis.",
    ["SAAP Septic Arthritis Guidelines"],
    "Pediatrics",
    "Pediatric Orthopedics",
    "hard",
    true,
    "Pediatric Orthopedics",
    ["septic-arthritis", "irritable-hip"],
  ),
  createQuestion(
    "A 2-year-old child presents with fever and generalized tonic-clonic seizure lasting 5 minutes. The child was previously well. Post-ictal examination is normal. What is the most likely diagnosis?",
    {
      A: "Epilepsy",
      B: "Febrile seizure",
      C: "Meningitis",
      D: "Intracranial hemorrhage",
      E: "Febrile infection-related epilepsy syndrome",
    },
    "B",
    `Simple febrile seizure is most likely: age 6 months-5 years, fever >38°C, generalized tonic-clonic seizure <15 minutes, single episode in 24 hours, normal neurological examination.\n\nEpilepsy requires recurrent unprovoked seizures. Meningitis would have persistent altered consciousness or signs. ICH is rare without trauma. FIRES is severe, prolonged, and refractory.`,
    "Febrile seizure: 6 months-5 years, fever, generalized seizure <15 min, normal neuro exam. Benign, but exclude CNS infection.",
    ["AAP Febrile Seizure Guidelines 2011"],
    "Pediatrics",
    "Pediatric Medicine",
    "easy",
    true,
    "Seizures",
    ["febrile-seizure", "benign"],
  ),
  createQuestion(
    "A 6-year-old child presents with pallor, fatigue, and hepatosplenomegaly. CBC shows Hb 65 g/L, WBC 45 x10^9/L with blasts, platelets 30 x10^9/L. What is the most likely diagnosis?",
    {
      A: "Acute lymphoblastic leukemia",
      B: "Acute myeloid leukemia",
      C: "Aplastic anemia",
      D: "Idiopathic thrombocytopenic purpura",
      E: "Infectious mononucleosis",
    },
    "A",
    `Acute lymphoblastic leukemia (ALL) is the most common childhood malignancy. Presentation: cytopenias (anemia, thrombocytopenia), organomegaly, high WBC with blasts.\n\nAML is less common in children. Aplastic anemia has pancytopenia without blasts. ITP has isolated thrombocytopenia. Mononucleosis has atypical lymphocytes, not blasts.`,
    "ALL: most common childhood cancer. Presentation with cytopenias, organomegaly, blasts on smear. Good prognosis with modern therapy.",
    ["COG ALL Guidelines"],
    "Pediatrics",
    "Pediatric Medicine",
    "medium",
    true,
    "Genetic Disorders",
    ["leukemia", "cytopenia"],
  ),
];

// Export combined questions
export const extendedQuestions = [
  ...endocrinologyQuestions,
  ...neurologyQuestions,
  ...obgynQuestions,
  ...pediatricsQuestions,
];
